/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.apis.AdminApi

class AdminApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AdminApi
        //val apiInstance = AdminApi()

        // to test getAdminSessionPacks
        should("test getAdminSessionPacks") {
            // uncomment below to test getAdminSessionPacks
            //val sessionId : kotlin.String = sessionId_example // kotlin.String | 
            //val xAdminToken : kotlin.String = xAdminToken_example // kotlin.String | 
            //apiInstance.getAdminSessionPacks(sessionId, xAdminToken)
        }

        // to test listAdminReceipts
        should("test listAdminReceipts") {
            // uncomment below to test listAdminReceipts
            //val xAdminToken : kotlin.String = xAdminToken_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val productId : kotlin.String = productId_example // kotlin.String | 
            //val storefront : kotlin.String = storefront_example // kotlin.String | 
            //val sessionId : kotlin.String = sessionId_example // kotlin.String | 
            //val since : kotlin.Long = 789 // kotlin.Long | Epoch milliseconds (inclusive lower bound)
            //val until : kotlin.Long = 789 // kotlin.Long | Epoch milliseconds (inclusive upper bound)
            //apiInstance.listAdminReceipts(xAdminToken, limit, productId, storefront, sessionId, since, until)
        }

    }
}
