/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.apis.HealthApi
import com.xai.dungeonmaster.client.models.HealthEnvelope
import com.xai.dungeonmaster.client.models.LivenessResponse
import com.xai.dungeonmaster.client.models.ReadinessResponse

class HealthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HealthApi
        //val apiInstance = HealthApi()

        // to test getHealthV2
        should("test getHealthV2") {
            // uncomment below to test getHealthV2
            //val xRequestId : kotlin.String = xRequestId_example // kotlin.String | Optional correlation id echoed back in the response envelope's requestId. A server-generated UUID is used when omitted. 
            //val result : HealthEnvelope = apiInstance.getHealthV2(xRequestId)
            //result shouldBe ("TODO")
        }

        // to test getLiveness
        should("test getLiveness") {
            // uncomment below to test getLiveness
            //val result : LivenessResponse = apiInstance.getLiveness()
            //result shouldBe ("TODO")
        }

        // to test getReadiness
        should("test getReadiness") {
            // uncomment below to test getReadiness
            //val result : ReadinessResponse = apiInstance.getReadiness()
            //result shouldBe ("TODO")
        }

        // to test getReadinessAlias
        should("test getReadinessAlias") {
            // uncomment below to test getReadinessAlias
            //val result : ReadinessResponse = apiInstance.getReadinessAlias()
            //result shouldBe ("TODO")
        }

    }
}
