/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.apis.HealthApi
import com.xai.dungeonmaster.client.models.LivenessResponse
import com.xai.dungeonmaster.client.models.ReadinessResponse

class HealthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HealthApi
        //val apiInstance = HealthApi()

        // to test getLiveness
        should("test getLiveness") {
            // uncomment below to test getLiveness
            //val result : LivenessResponse = apiInstance.getLiveness()
            //result shouldBe ("TODO")
        }

        // to test getPrometheusMetrics
        should("test getPrometheusMetrics") {
            // uncomment below to test getPrometheusMetrics
            //val xMetricsToken : kotlin.String = xMetricsToken_example // kotlin.String | Metrics scrape token (`game.metrics.scrape-token`). Alternative to `Authorization: Bearer <token>`. Unlocks readiness/v2 health detail fields. 
            //val authorization : kotlin.String = authorization_example // kotlin.String | Bearer scrape token (alternative to X-Metrics-Token).
            //val result : kotlin.String = apiInstance.getPrometheusMetrics(xMetricsToken, authorization)
            //result shouldBe ("TODO")
        }

        // to test getReadiness
        should("test getReadiness") {
            // uncomment below to test getReadiness
            //val xMetricsToken : kotlin.String = xMetricsToken_example // kotlin.String | Metrics scrape token (`game.metrics.scrape-token`). Alternative to `Authorization: Bearer <token>`. Unlocks readiness/v2 health detail fields. 
            //val xAdminToken : kotlin.String = xAdminToken_example // kotlin.String | Ops shared secret (`game.admin.token`). During rotation, `game.admin.token.previous` is also accepted. Required for admin routes and (in prod) catalog pack upload; unlocks health recon detail. 
            //val result : ReadinessResponse = apiInstance.getReadiness(xMetricsToken, xAdminToken)
            //result shouldBe ("TODO")
        }

        // to test getReadinessAlias
        should("test getReadinessAlias") {
            // uncomment below to test getReadinessAlias
            //val xMetricsToken : kotlin.String = xMetricsToken_example // kotlin.String | Metrics scrape token (`game.metrics.scrape-token`). Alternative to `Authorization: Bearer <token>`. Unlocks readiness/v2 health detail fields. 
            //val xAdminToken : kotlin.String = xAdminToken_example // kotlin.String | Ops shared secret (`game.admin.token`). During rotation, `game.admin.token.previous` is also accepted. Required for admin routes and (in prod) catalog pack upload; unlocks health recon detail. 
            //val result : ReadinessResponse = apiInstance.getReadinessAlias(xMetricsToken, xAdminToken)
            //result shouldBe ("TODO")
        }

    }
}
