/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.apis.LegacyApi
import com.xai.dungeonmaster.client.models.ActionRequest
import com.xai.dungeonmaster.client.models.GameStatusResponse

class LegacyApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LegacyApi
        //val apiInstance = LegacyApi()

        // to test getChoicesLegacy
        should("test getChoicesLegacy") {
            // uncomment below to test getChoicesLegacy
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.getChoicesLegacy()
            //result shouldBe ("TODO")
        }

        // to test getStatusLegacy
        should("test getStatusLegacy") {
            // uncomment below to test getStatusLegacy
            //val result : GameStatusResponse = apiInstance.getStatusLegacy()
            //result shouldBe ("TODO")
        }

        // to test loadGameLegacy
        should("test loadGameLegacy") {
            // uncomment below to test loadGameLegacy
            //val result : kotlin.String = apiInstance.loadGameLegacy()
            //result shouldBe ("TODO")
        }

        // to test saveGameLegacy
        should("test saveGameLegacy") {
            // uncomment below to test saveGameLegacy
            //val result : kotlin.String = apiInstance.saveGameLegacy()
            //result shouldBe ("TODO")
        }

        // to test startQuestLegacy
        should("test startQuestLegacy") {
            // uncomment below to test startQuestLegacy
            //val result : kotlin.String = apiInstance.startQuestLegacy()
            //result shouldBe ("TODO")
        }

        // to test submitActionLegacy
        should("test submitActionLegacy") {
            // uncomment below to test submitActionLegacy
            //val actionRequest : ActionRequest =  // ActionRequest | 
            //val result : kotlin.String = apiInstance.submitActionLegacy(actionRequest)
            //result shouldBe ("TODO")
        }

    }
}
