/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.apis.V2Api
import com.xai.dungeonmaster.client.models.ActionRequest
import com.xai.dungeonmaster.client.models.CatalogEnvelope
import com.xai.dungeonmaster.client.models.ErrorEnvelope
import com.xai.dungeonmaster.client.models.GameStatusEnvelope
import com.xai.dungeonmaster.client.models.NarrateRequest
import com.xai.dungeonmaster.client.models.NarrativeEnvelope

class V2ApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of V2Api
        //val apiInstance = V2Api()

        // to test getCatalogV2
        should("test getCatalogV2") {
            // uncomment below to test getCatalogV2
            //val xRequestId : kotlin.String = xRequestId_example // kotlin.String | Optional correlation id echoed back in the response envelope's requestId. A server-generated UUID is used when omitted. 
            //val result : CatalogEnvelope = apiInstance.getCatalogV2(xRequestId)
            //result shouldBe ("TODO")
        }

        // to test getStatusV2
        should("test getStatusV2") {
            // uncomment below to test getStatusV2
            //val xRequestId : kotlin.String = xRequestId_example // kotlin.String | Optional correlation id echoed back in the response envelope's requestId. A server-generated UUID is used when omitted. 
            //val result : GameStatusEnvelope = apiInstance.getStatusV2(xRequestId)
            //result shouldBe ("TODO")
        }

        // to test narrateV2
        should("test narrateV2") {
            // uncomment below to test narrateV2
            //val xRequestId : kotlin.String = xRequestId_example // kotlin.String | Optional correlation id echoed back in the response envelope's requestId. A server-generated UUID is used when omitted. 
            //val narrateRequest : NarrateRequest =  // NarrateRequest | 
            //val result : NarrativeEnvelope = apiInstance.narrateV2(xRequestId, narrateRequest)
            //result shouldBe ("TODO")
        }

        // to test submitActionV2
        should("test submitActionV2") {
            // uncomment below to test submitActionV2
            //val actionRequest : ActionRequest =  // ActionRequest | 
            //val xRequestId : kotlin.String = xRequestId_example // kotlin.String | Optional correlation id echoed back in the response envelope's requestId. A server-generated UUID is used when omitted. 
            //val result : GameStatusEnvelope = apiInstance.submitActionV2(actionRequest, xRequestId)
            //result shouldBe ("TODO")
        }

    }
}
