/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminAuditEventsPayload } from './AdminAuditEventsPayload';
import {
    AdminAuditEventsPayloadFromJSON,
    AdminAuditEventsPayloadFromJSONTyped,
    AdminAuditEventsPayloadToJSON,
} from './AdminAuditEventsPayload';

/**
 * 
 * @export
 * @interface AdminAuditEventsEnvelope
 */
export interface AdminAuditEventsEnvelope {
    /**
     * 
     * @type {string}
     * @memberof AdminAuditEventsEnvelope
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof AdminAuditEventsEnvelope
     */
    version: number;
    /**
     * 
     * @type {AdminAuditEventsPayload}
     * @memberof AdminAuditEventsEnvelope
     */
    payload: AdminAuditEventsPayload;
    /**
     * 
     * @type {string}
     * @memberof AdminAuditEventsEnvelope
     */
    requestId: string;
}

/**
 * Check if a given object implements the AdminAuditEventsEnvelope interface.
 */
export function instanceOfAdminAuditEventsEnvelope(value: object): value is AdminAuditEventsEnvelope {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function AdminAuditEventsEnvelopeFromJSON(json: any): AdminAuditEventsEnvelope {
    return AdminAuditEventsEnvelopeFromJSONTyped(json, false);
}

export function AdminAuditEventsEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuditEventsEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'version': json['version'],
        'payload': AdminAuditEventsPayloadFromJSON(json['payload']),
        'requestId': json['requestId'],
    };
}

export function AdminAuditEventsEnvelopeToJSON(value?: AdminAuditEventsEnvelope | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'version': value['version'],
        'payload': AdminAuditEventsPayloadToJSON(value['payload']),
        'requestId': value['requestId'],
    };
}

