/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminAuditEvent } from './AdminAuditEvent';
import {
    AdminAuditEventFromJSON,
    AdminAuditEventFromJSONTyped,
    AdminAuditEventToJSON,
} from './AdminAuditEvent';

/**
 * 
 * @export
 * @interface AdminAuditEventsPayload
 */
export interface AdminAuditEventsPayload {
    /**
     * 
     * @type {number}
     * @memberof AdminAuditEventsPayload
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminAuditEventsPayload
     */
    limit?: number;
    /**
     * 
     * @type {Array<AdminAuditEvent>}
     * @memberof AdminAuditEventsPayload
     */
    events?: Array<AdminAuditEvent>;
}

/**
 * Check if a given object implements the AdminAuditEventsPayload interface.
 */
export function instanceOfAdminAuditEventsPayload(value: object): value is AdminAuditEventsPayload {
    return true;
}

export function AdminAuditEventsPayloadFromJSON(json: any): AdminAuditEventsPayload {
    return AdminAuditEventsPayloadFromJSONTyped(json, false);
}

export function AdminAuditEventsPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuditEventsPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'events': json['events'] == null ? undefined : ((json['events'] as Array<any>).map(AdminAuditEventFromJSON)),
    };
}

export function AdminAuditEventsPayloadToJSON(value?: AdminAuditEventsPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'limit': value['limit'],
        'events': value['events'] == null ? undefined : ((value['events'] as Array<any>).map(AdminAuditEventToJSON)),
    };
}

