/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminSessionPacksPayload } from './AdminSessionPacksPayload';
import {
    AdminSessionPacksPayloadFromJSON,
    AdminSessionPacksPayloadFromJSONTyped,
    AdminSessionPacksPayloadToJSON,
} from './AdminSessionPacksPayload';

/**
 * 
 * @export
 * @interface AdminSessionPacksEnvelope
 */
export interface AdminSessionPacksEnvelope {
    /**
     * 
     * @type {string}
     * @memberof AdminSessionPacksEnvelope
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof AdminSessionPacksEnvelope
     */
    version: number;
    /**
     * 
     * @type {AdminSessionPacksPayload}
     * @memberof AdminSessionPacksEnvelope
     */
    payload: AdminSessionPacksPayload;
    /**
     * 
     * @type {string}
     * @memberof AdminSessionPacksEnvelope
     */
    requestId: string;
}

/**
 * Check if a given object implements the AdminSessionPacksEnvelope interface.
 */
export function instanceOfAdminSessionPacksEnvelope(value: object): value is AdminSessionPacksEnvelope {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function AdminSessionPacksEnvelopeFromJSON(json: any): AdminSessionPacksEnvelope {
    return AdminSessionPacksEnvelopeFromJSONTyped(json, false);
}

export function AdminSessionPacksEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSessionPacksEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'version': json['version'],
        'payload': AdminSessionPacksPayloadFromJSON(json['payload']),
        'requestId': json['requestId'],
    };
}

export function AdminSessionPacksEnvelopeToJSON(value?: AdminSessionPacksEnvelope | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'version': value['version'],
        'payload': AdminSessionPacksPayloadToJSON(value['payload']),
        'requestId': value['requestId'],
    };
}

