/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminReceiptRow
 */
export interface AdminReceiptRow {
    /**
     * 
     * @type {string}
     * @memberof AdminReceiptRow
     */
    fingerprint?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminReceiptRow
     */
    sessionId?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminReceiptRow
     */
    productId?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminReceiptRow
     */
    storefront?: string;
    /**
     * 
     * @type {number}
     * @memberof AdminReceiptRow
     */
    redeemedAtEpochMs?: number;
}

/**
 * Check if a given object implements the AdminReceiptRow interface.
 */
export function instanceOfAdminReceiptRow(value: object): value is AdminReceiptRow {
    return true;
}

export function AdminReceiptRowFromJSON(json: any): AdminReceiptRow {
    return AdminReceiptRowFromJSONTyped(json, false);
}

export function AdminReceiptRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminReceiptRow {
    if (json == null) {
        return json;
    }
    return {
        
        'fingerprint': json['fingerprint'] == null ? undefined : json['fingerprint'],
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'storefront': json['storefront'] == null ? undefined : json['storefront'],
        'redeemedAtEpochMs': json['redeemedAtEpochMs'] == null ? undefined : json['redeemedAtEpochMs'],
    };
}

export function AdminReceiptRowToJSON(value?: AdminReceiptRow | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fingerprint': value['fingerprint'],
        'sessionId': value['sessionId'],
        'productId': value['productId'],
        'storefront': value['storefront'],
        'redeemedAtEpochMs': value['redeemedAtEpochMs'],
    };
}

