/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminAuditEvent
 */
export interface AdminAuditEvent {
    /**
     * 
     * @type {number}
     * @memberof AdminAuditEvent
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminAuditEvent
     */
    atEpochMs?: number;
    /**
     * 
     * @type {string}
     * @memberof AdminAuditEvent
     */
    outcome?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuditEvent
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuditEvent
     */
    clientIp?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuditEvent
     */
    requestId?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuditEvent
     */
    detail?: string;
}

/**
 * Check if a given object implements the AdminAuditEvent interface.
 */
export function instanceOfAdminAuditEvent(value: object): value is AdminAuditEvent {
    return true;
}

export function AdminAuditEventFromJSON(json: any): AdminAuditEvent {
    return AdminAuditEventFromJSONTyped(json, false);
}

export function AdminAuditEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuditEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'atEpochMs': json['atEpochMs'] == null ? undefined : json['atEpochMs'],
        'outcome': json['outcome'] == null ? undefined : json['outcome'],
        'path': json['path'] == null ? undefined : json['path'],
        'clientIp': json['clientIp'] == null ? undefined : json['clientIp'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function AdminAuditEventToJSON(value?: AdminAuditEvent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'atEpochMs': value['atEpochMs'],
        'outcome': value['outcome'],
        'path': value['path'],
        'clientIp': value['clientIp'],
        'requestId': value['requestId'],
        'detail': value['detail'],
    };
}

