/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminSessionRow } from './AdminSessionRow';
import {
    AdminSessionRowFromJSON,
    AdminSessionRowFromJSONTyped,
    AdminSessionRowToJSON,
} from './AdminSessionRow';

/**
 * 
 * @export
 * @interface AdminSessionsPayload
 */
export interface AdminSessionsPayload {
    /**
     * 
     * @type {number}
     * @memberof AdminSessionsPayload
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminSessionsPayload
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminSessionsPayload
     */
    limit?: number;
    /**
     * 
     * @type {Array<AdminSessionRow>}
     * @memberof AdminSessionsPayload
     */
    sessions?: Array<AdminSessionRow>;
}

/**
 * Check if a given object implements the AdminSessionsPayload interface.
 */
export function instanceOfAdminSessionsPayload(value: object): value is AdminSessionsPayload {
    return true;
}

export function AdminSessionsPayloadFromJSON(json: any): AdminSessionsPayload {
    return AdminSessionsPayloadFromJSONTyped(json, false);
}

export function AdminSessionsPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSessionsPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'total': json['total'] == null ? undefined : json['total'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'sessions': json['sessions'] == null ? undefined : ((json['sessions'] as Array<any>).map(AdminSessionRowFromJSON)),
    };
}

export function AdminSessionsPayloadToJSON(value?: AdminSessionsPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'total': value['total'],
        'limit': value['limit'],
        'sessions': value['sessions'] == null ? undefined : ((value['sessions'] as Array<any>).map(AdminSessionRowToJSON)),
    };
}

