/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminSessionPacksPayload
 */
export interface AdminSessionPacksPayload {
    /**
     * 
     * @type {string}
     * @memberof AdminSessionPacksPayload
     */
    sessionId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminSessionPacksPayload
     */
    enabledPackIds?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AdminSessionPacksPayload
     */
    overrides?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof AdminSessionPacksPayload
     */
    sessionScoped?: boolean;
}

/**
 * Check if a given object implements the AdminSessionPacksPayload interface.
 */
export function instanceOfAdminSessionPacksPayload(value: object): value is AdminSessionPacksPayload {
    return true;
}

export function AdminSessionPacksPayloadFromJSON(json: any): AdminSessionPacksPayload {
    return AdminSessionPacksPayloadFromJSONTyped(json, false);
}

export function AdminSessionPacksPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSessionPacksPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'enabledPackIds': json['enabledPackIds'] == null ? undefined : json['enabledPackIds'],
        'overrides': json['overrides'] == null ? undefined : json['overrides'],
        'sessionScoped': json['sessionScoped'] == null ? undefined : json['sessionScoped'],
    };
}

export function AdminSessionPacksPayloadToJSON(value?: AdminSessionPacksPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sessionId': value['sessionId'],
        'enabledPackIds': value['enabledPackIds'],
        'overrides': value['overrides'],
        'sessionScoped': value['sessionScoped'],
    };
}

