/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminReceiptsPayload } from './AdminReceiptsPayload';
import {
    AdminReceiptsPayloadFromJSON,
    AdminReceiptsPayloadFromJSONTyped,
    AdminReceiptsPayloadToJSON,
} from './AdminReceiptsPayload';

/**
 * 
 * @export
 * @interface AdminReceiptsEnvelope
 */
export interface AdminReceiptsEnvelope {
    /**
     * 
     * @type {string}
     * @memberof AdminReceiptsEnvelope
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof AdminReceiptsEnvelope
     */
    version: number;
    /**
     * 
     * @type {AdminReceiptsPayload}
     * @memberof AdminReceiptsEnvelope
     */
    payload: AdminReceiptsPayload;
    /**
     * 
     * @type {string}
     * @memberof AdminReceiptsEnvelope
     */
    requestId: string;
}

/**
 * Check if a given object implements the AdminReceiptsEnvelope interface.
 */
export function instanceOfAdminReceiptsEnvelope(value: object): value is AdminReceiptsEnvelope {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function AdminReceiptsEnvelopeFromJSON(json: any): AdminReceiptsEnvelope {
    return AdminReceiptsEnvelopeFromJSONTyped(json, false);
}

export function AdminReceiptsEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminReceiptsEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'version': json['version'],
        'payload': AdminReceiptsPayloadFromJSON(json['payload']),
        'requestId': json['requestId'],
    };
}

export function AdminReceiptsEnvelopeToJSON(value?: AdminReceiptsEnvelope | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'version': value['version'],
        'payload': AdminReceiptsPayloadToJSON(value['payload']),
        'requestId': value['requestId'],
    };
}

