/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminSecurityEventsPayload } from './AdminSecurityEventsPayload';
import {
    AdminSecurityEventsPayloadFromJSON,
    AdminSecurityEventsPayloadFromJSONTyped,
    AdminSecurityEventsPayloadToJSON,
} from './AdminSecurityEventsPayload';

/**
 * 
 * @export
 * @interface AdminSecurityEventsEnvelope
 */
export interface AdminSecurityEventsEnvelope {
    /**
     * 
     * @type {string}
     * @memberof AdminSecurityEventsEnvelope
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof AdminSecurityEventsEnvelope
     */
    version: number;
    /**
     * 
     * @type {AdminSecurityEventsPayload}
     * @memberof AdminSecurityEventsEnvelope
     */
    payload: AdminSecurityEventsPayload;
    /**
     * 
     * @type {string}
     * @memberof AdminSecurityEventsEnvelope
     */
    requestId: string;
}

/**
 * Check if a given object implements the AdminSecurityEventsEnvelope interface.
 */
export function instanceOfAdminSecurityEventsEnvelope(value: object): value is AdminSecurityEventsEnvelope {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function AdminSecurityEventsEnvelopeFromJSON(json: any): AdminSecurityEventsEnvelope {
    return AdminSecurityEventsEnvelopeFromJSONTyped(json, false);
}

export function AdminSecurityEventsEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSecurityEventsEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'version': json['version'],
        'payload': AdminSecurityEventsPayloadFromJSON(json['payload']),
        'requestId': json['requestId'],
    };
}

export function AdminSecurityEventsEnvelopeToJSON(value?: AdminSecurityEventsEnvelope | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'version': value['version'],
        'payload': AdminSecurityEventsPayloadToJSON(value['payload']),
        'requestId': value['requestId'],
    };
}

