/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminSessionsPayload } from './AdminSessionsPayload';
import {
    AdminSessionsPayloadFromJSON,
    AdminSessionsPayloadFromJSONTyped,
    AdminSessionsPayloadToJSON,
} from './AdminSessionsPayload';

/**
 * 
 * @export
 * @interface AdminSessionsEnvelope
 */
export interface AdminSessionsEnvelope {
    /**
     * 
     * @type {string}
     * @memberof AdminSessionsEnvelope
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof AdminSessionsEnvelope
     */
    version: number;
    /**
     * 
     * @type {AdminSessionsPayload}
     * @memberof AdminSessionsEnvelope
     */
    payload: AdminSessionsPayload;
    /**
     * 
     * @type {string}
     * @memberof AdminSessionsEnvelope
     */
    requestId: string;
}

/**
 * Check if a given object implements the AdminSessionsEnvelope interface.
 */
export function instanceOfAdminSessionsEnvelope(value: object): value is AdminSessionsEnvelope {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function AdminSessionsEnvelopeFromJSON(json: any): AdminSessionsEnvelope {
    return AdminSessionsEnvelopeFromJSONTyped(json, false);
}

export function AdminSessionsEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSessionsEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'version': json['version'],
        'payload': AdminSessionsPayloadFromJSON(json['payload']),
        'requestId': json['requestId'],
    };
}

export function AdminSessionsEnvelopeToJSON(value?: AdminSessionsEnvelope | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'version': value['version'],
        'payload': AdminSessionsPayloadToJSON(value['payload']),
        'requestId': value['requestId'],
    };
}

