/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DependencyCheck
 */
export interface DependencyCheck {
    /**
     * 
     * @type {string}
     * @memberof DependencyCheck
     */
    status: DependencyCheckStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof DependencyCheck
     */
    detail?: string;
}


/**
 * @export
 */
export const DependencyCheckStatusEnum = {
    Up: 'UP',
    Down: 'DOWN',
    NotConfigured: 'NOT_CONFIGURED'
} as const;
export type DependencyCheckStatusEnum = typeof DependencyCheckStatusEnum[keyof typeof DependencyCheckStatusEnum];


/**
 * Check if a given object implements the DependencyCheck interface.
 */
export function instanceOfDependencyCheck(value: object): value is DependencyCheck {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DependencyCheckFromJSON(json: any): DependencyCheck {
    return DependencyCheckFromJSONTyped(json, false);
}

export function DependencyCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): DependencyCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function DependencyCheckToJSON(value?: DependencyCheck | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'detail': value['detail'],
    };
}

