/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberState } from './MemberState';
import {
    MemberStateFromJSON,
    MemberStateFromJSONTyped,
    MemberStateToJSON,
} from './MemberState';
import type { QuestInfo } from './QuestInfo';
import {
    QuestInfoFromJSON,
    QuestInfoFromJSONTyped,
    QuestInfoToJSON,
} from './QuestInfo';

/**
 * 
 * @export
 * @interface GameStatusV2
 */
export interface GameStatusV2 {
    /**
     * 
     * @type {Array<MemberState>}
     * @memberof GameStatusV2
     */
    party?: Array<MemberState>;
    /**
     * 
     * @type {number}
     * @memberof GameStatusV2
     */
    chaosLevel?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GameStatusV2
     */
    combatActive?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof GameStatusV2
     */
    availableChoices?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GameStatusV2
     */
    recentHistory?: Array<string>;
    /**
     * 
     * @type {QuestInfo}
     * @memberof GameStatusV2
     */
    quest?: QuestInfo | null;
    /**
     * Compact story-memory facts from the engine's Chronicle (newest last), e.g. "Quest completed: The Weeping Tree". Bounded server-side.
     * @type {Array<string>}
     * @memberof GameStatusV2
     */
    recentEvents?: Array<string>;
}

/**
 * Check if a given object implements the GameStatusV2 interface.
 */
export function instanceOfGameStatusV2(value: object): value is GameStatusV2 {
    return true;
}

export function GameStatusV2FromJSON(json: any): GameStatusV2 {
    return GameStatusV2FromJSONTyped(json, false);
}

export function GameStatusV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStatusV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'party': json['party'] == null ? undefined : ((json['party'] as Array<any>).map(MemberStateFromJSON)),
        'chaosLevel': json['chaosLevel'] == null ? undefined : json['chaosLevel'],
        'combatActive': json['combatActive'] == null ? undefined : json['combatActive'],
        'availableChoices': json['availableChoices'] == null ? undefined : json['availableChoices'],
        'recentHistory': json['recentHistory'] == null ? undefined : json['recentHistory'],
        'quest': json['quest'] == null ? undefined : QuestInfoFromJSON(json['quest']),
        'recentEvents': json['recentEvents'] == null ? undefined : json['recentEvents'],
    };
}

export function GameStatusV2ToJSON(value?: GameStatusV2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'party': value['party'] == null ? undefined : ((value['party'] as Array<any>).map(MemberStateToJSON)),
        'chaosLevel': value['chaosLevel'],
        'combatActive': value['combatActive'],
        'availableChoices': value['availableChoices'],
        'recentHistory': value['recentHistory'],
        'quest': QuestInfoToJSON(value['quest']),
        'recentEvents': value['recentEvents'],
    };
}

