/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DependencyCheck } from './DependencyCheck';
import {
    DependencyCheckFromJSON,
    DependencyCheckFromJSONTyped,
    DependencyCheckToJSON,
} from './DependencyCheck';
import type { HealthPayloadMemory } from './HealthPayloadMemory';
import {
    HealthPayloadMemoryFromJSON,
    HealthPayloadMemoryFromJSONTyped,
    HealthPayloadMemoryToJSON,
} from './HealthPayloadMemory';

/**
 * 
 * @export
 * @interface HealthPayload
 */
export interface HealthPayload {
    /**
     * 
     * @type {string}
     * @memberof HealthPayload
     */
    status: HealthPayloadStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof HealthPayload
     */
    uptimeSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof HealthPayload
     */
    sessions?: number;
    /**
     * 
     * @type {number}
     * @memberof HealthPayload
     */
    engines?: number;
    /**
     * 
     * @type {{ [key: string]: DependencyCheck; }}
     * @memberof HealthPayload
     */
    dependencies?: { [key: string]: DependencyCheck; };
    /**
     * 
     * @type {HealthPayloadMemory}
     * @memberof HealthPayload
     */
    memory?: HealthPayloadMemory;
}


/**
 * @export
 */
export const HealthPayloadStatusEnum = {
    Up: 'UP',
    Down: 'DOWN'
} as const;
export type HealthPayloadStatusEnum = typeof HealthPayloadStatusEnum[keyof typeof HealthPayloadStatusEnum];


/**
 * Check if a given object implements the HealthPayload interface.
 */
export function instanceOfHealthPayload(value: object): value is HealthPayload {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function HealthPayloadFromJSON(json: any): HealthPayload {
    return HealthPayloadFromJSONTyped(json, false);
}

export function HealthPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'uptimeSeconds': json['uptimeSeconds'] == null ? undefined : json['uptimeSeconds'],
        'sessions': json['sessions'] == null ? undefined : json['sessions'],
        'engines': json['engines'] == null ? undefined : json['engines'],
        'dependencies': json['dependencies'] == null ? undefined : (mapValues(json['dependencies'], DependencyCheckFromJSON)),
        'memory': json['memory'] == null ? undefined : HealthPayloadMemoryFromJSON(json['memory']),
    };
}

export function HealthPayloadToJSON(value?: HealthPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'uptimeSeconds': value['uptimeSeconds'],
        'sessions': value['sessions'],
        'engines': value['engines'],
        'dependencies': value['dependencies'] == null ? undefined : (mapValues(value['dependencies'], DependencyCheckToJSON)),
        'memory': HealthPayloadMemoryToJSON(value['memory']),
    };
}

