/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketplaceInstallJob } from './MarketplaceInstallJob';
import {
    MarketplaceInstallJobFromJSON,
    MarketplaceInstallJobFromJSONTyped,
    MarketplaceInstallJobToJSON,
} from './MarketplaceInstallJob';

/**
 * 
 * @export
 * @interface MarketplaceInstallJobEnvelope
 */
export interface MarketplaceInstallJobEnvelope {
    /**
     * 
     * @type {string}
     * @memberof MarketplaceInstallJobEnvelope
     */
    type: MarketplaceInstallJobEnvelopeTypeEnum;
    /**
     * Schema version of the payload contract.
     * @type {number}
     * @memberof MarketplaceInstallJobEnvelope
     */
    version: number;
    /**
     * 
     * @type {MarketplaceInstallJob}
     * @memberof MarketplaceInstallJobEnvelope
     */
    payload: MarketplaceInstallJob;
    /**
     * Correlation id (echoed from X-Request-Id or generated).
     * @type {string}
     * @memberof MarketplaceInstallJobEnvelope
     */
    requestId: string;
}


/**
 * @export
 */
export const MarketplaceInstallJobEnvelopeTypeEnum = {
    MarketplaceInstallJob: 'marketplace_install_job'
} as const;
export type MarketplaceInstallJobEnvelopeTypeEnum = typeof MarketplaceInstallJobEnvelopeTypeEnum[keyof typeof MarketplaceInstallJobEnvelopeTypeEnum];


/**
 * Check if a given object implements the MarketplaceInstallJobEnvelope interface.
 */
export function instanceOfMarketplaceInstallJobEnvelope(value: object): value is MarketplaceInstallJobEnvelope {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function MarketplaceInstallJobEnvelopeFromJSON(json: any): MarketplaceInstallJobEnvelope {
    return MarketplaceInstallJobEnvelopeFromJSONTyped(json, false);
}

export function MarketplaceInstallJobEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketplaceInstallJobEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'version': json['version'],
        'payload': MarketplaceInstallJobFromJSON(json['payload']),
        'requestId': json['requestId'],
    };
}

export function MarketplaceInstallJobEnvelopeToJSON(value?: MarketplaceInstallJobEnvelope | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'version': value['version'],
        'payload': MarketplaceInstallJobToJSON(value['payload']),
        'requestId': value['requestId'],
    };
}

