/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketplaceInstallJob } from './MarketplaceInstallJob';
import {
    MarketplaceInstallJobFromJSON,
    MarketplaceInstallJobFromJSONTyped,
    MarketplaceInstallJobToJSON,
} from './MarketplaceInstallJob';

/**
 * 
 * @export
 * @interface MarketplaceInstallJobsPayload
 */
export interface MarketplaceInstallJobsPayload {
    /**
     * 
     * @type {number}
     * @memberof MarketplaceInstallJobsPayload
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof MarketplaceInstallJobsPayload
     */
    limit?: number;
    /**
     * 
     * @type {Array<MarketplaceInstallJob>}
     * @memberof MarketplaceInstallJobsPayload
     */
    jobs?: Array<MarketplaceInstallJob>;
}

/**
 * Check if a given object implements the MarketplaceInstallJobsPayload interface.
 */
export function instanceOfMarketplaceInstallJobsPayload(value: object): value is MarketplaceInstallJobsPayload {
    return true;
}

export function MarketplaceInstallJobsPayloadFromJSON(json: any): MarketplaceInstallJobsPayload {
    return MarketplaceInstallJobsPayloadFromJSONTyped(json, false);
}

export function MarketplaceInstallJobsPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketplaceInstallJobsPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'jobs': json['jobs'] == null ? undefined : ((json['jobs'] as Array<any>).map(MarketplaceInstallJobFromJSON)),
    };
}

export function MarketplaceInstallJobsPayloadToJSON(value?: MarketplaceInstallJobsPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'limit': value['limit'],
        'jobs': value['jobs'] == null ? undefined : ((value['jobs'] as Array<any>).map(MarketplaceInstallJobToJSON)),
    };
}

