/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NarrativePayload } from './NarrativePayload';
import {
    NarrativePayloadFromJSON,
    NarrativePayloadFromJSONTyped,
    NarrativePayloadToJSON,
} from './NarrativePayload';

/**
 * 
 * @export
 * @interface NarrativeEnvelope
 */
export interface NarrativeEnvelope {
    /**
     * 
     * @type {string}
     * @memberof NarrativeEnvelope
     */
    type: string;
    /**
     * Schema version of the payload contract.
     * @type {number}
     * @memberof NarrativeEnvelope
     */
    version: number;
    /**
     * 
     * @type {NarrativePayload}
     * @memberof NarrativeEnvelope
     */
    payload: NarrativePayload;
    /**
     * Correlation id (echoed from X-Request-Id or generated).
     * @type {string}
     * @memberof NarrativeEnvelope
     */
    requestId: string;
}

/**
 * Check if a given object implements the NarrativeEnvelope interface.
 */
export function instanceOfNarrativeEnvelope(value: object): value is NarrativeEnvelope {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function NarrativeEnvelopeFromJSON(json: any): NarrativeEnvelope {
    return NarrativeEnvelopeFromJSONTyped(json, false);
}

export function NarrativeEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NarrativeEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'version': json['version'],
        'payload': NarrativePayloadFromJSON(json['payload']),
        'requestId': json['requestId'],
    };
}

export function NarrativeEnvelopeToJSON(value?: NarrativeEnvelope | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'version': value['version'],
        'payload': NarrativePayloadToJSON(value['payload']),
        'requestId': value['requestId'],
    };
}

