/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Goal G2 — player-facing identity and session recap.
 * @export
 * @interface StoryMemoryPayload
 */
export interface StoryMemoryPayload {
    /**
     * e.g. "Ryn the Ash-Handed"
     * @type {string}
     * @memberof StoryMemoryPayload
     */
    partyTitle?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StoryMemoryPayload
     */
    epithets?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof StoryMemoryPayload
     */
    scars?: Array<string>;
    /**
     * Up to ~3 short sentences for load / chrome.
     * @type {Array<string>}
     * @memberof StoryMemoryPayload
     */
    recap?: Array<string>;
}

/**
 * Check if a given object implements the StoryMemoryPayload interface.
 */
export function instanceOfStoryMemoryPayload(value: object): value is StoryMemoryPayload {
    return true;
}

export function StoryMemoryPayloadFromJSON(json: any): StoryMemoryPayload {
    return StoryMemoryPayloadFromJSONTyped(json, false);
}

export function StoryMemoryPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryMemoryPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'partyTitle': json['partyTitle'] == null ? undefined : json['partyTitle'],
        'epithets': json['epithets'] == null ? undefined : json['epithets'],
        'scars': json['scars'] == null ? undefined : json['scars'],
        'recap': json['recap'] == null ? undefined : json['recap'],
    };
}

export function StoryMemoryPayloadToJSON(value?: StoryMemoryPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'partyTitle': value['partyTitle'],
        'epithets': value['epithets'],
        'scars': value['scars'],
        'recap': value['recap'],
    };
}

