//
// AdminAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AdminAPI {

    /**
     Session pack overrides (ops)
     
     - parameter sessionId: (query)  
     - parameter xAdminToken: (header)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getAdminSessionPacks(sessionId: String, xAdminToken: String) async throws {
        return try await getAdminSessionPacksWithRequestBuilder(sessionId: sessionId, xAdminToken: xAdminToken).execute().body
    }

    /**
     Session pack overrides (ops)
     - GET /v2/admin/session-packs
     - parameter sessionId: (query)  
     - parameter xAdminToken: (header)  
     - returns: RequestBuilder<Void> 
     */
    open class func getAdminSessionPacksWithRequestBuilder(sessionId: String, xAdminToken: String) -> RequestBuilder<Void> {
        let localVariablePath = "/v2/admin/session-packs"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "sessionId": (wrappedValue: sessionId.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Admin-Token": xAdminToken.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     List recent redeemed receipts (ops)
     
     - parameter xAdminToken: (header)  
     - parameter limit: (query)  (optional, default to 50)
     - parameter productId: (query)  (optional)
     - parameter storefront: (query)  (optional)
     - parameter sessionId: (query)  (optional)
     - parameter since: (query) Epoch milliseconds (inclusive lower bound) (optional)
     - parameter until: (query) Epoch milliseconds (inclusive upper bound) (optional)
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listAdminReceipts(xAdminToken: String, limit: Int? = nil, productId: String? = nil, storefront: String? = nil, sessionId: String? = nil, since: Int64? = nil, until: Int64? = nil) async throws {
        return try await listAdminReceiptsWithRequestBuilder(xAdminToken: xAdminToken, limit: limit, productId: productId, storefront: storefront, sessionId: sessionId, since: since, until: until).execute().body
    }

    /**
     List recent redeemed receipts (ops)
     - GET /v2/admin/receipts
     - parameter xAdminToken: (header)  
     - parameter limit: (query)  (optional, default to 50)
     - parameter productId: (query)  (optional)
     - parameter storefront: (query)  (optional)
     - parameter sessionId: (query)  (optional)
     - parameter since: (query) Epoch milliseconds (inclusive lower bound) (optional)
     - parameter until: (query) Epoch milliseconds (inclusive upper bound) (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func listAdminReceiptsWithRequestBuilder(xAdminToken: String, limit: Int? = nil, productId: String? = nil, storefront: String? = nil, sessionId: String? = nil, since: Int64? = nil, until: Int64? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/v2/admin/receipts"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "productId": (wrappedValue: productId?.encodeToJSON(), isExplode: true),
            "storefront": (wrappedValue: storefront?.encodeToJSON(), isExplode: true),
            "sessionId": (wrappedValue: sessionId?.encodeToJSON(), isExplode: true),
            "since": (wrappedValue: since?.encodeToJSON(), isExplode: true),
            "until": (wrappedValue: until?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Admin-Token": xAdminToken.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     List active sessions (ops)
     
     - parameter xAdminToken: (header)  
     - parameter limit: (query)  (optional, default to 100)
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: AdminSessionsEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listAdminSessions(xAdminToken: String, limit: Int? = nil, xRequestId: String? = nil) async throws -> AdminSessionsEnvelope {
        return try await listAdminSessionsWithRequestBuilder(xAdminToken: xAdminToken, limit: limit, xRequestId: xRequestId).execute().body
    }

    /**
     List active sessions (ops)
     - GET /v2/admin/sessions
     - Identity only — no JWTs. Newest last-seen first.
     - parameter xAdminToken: (header)  
     - parameter limit: (query)  (optional, default to 100)
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: RequestBuilder<AdminSessionsEnvelope> 
     */
    open class func listAdminSessionsWithRequestBuilder(xAdminToken: String, limit: Int? = nil, xRequestId: String? = nil) -> RequestBuilder<AdminSessionsEnvelope> {
        let localVariablePath = "/v2/admin/sessions"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Admin-Token": xAdminToken.encodeToJSON(),
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AdminSessionsEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Revoke a session (ops)
     
     - parameter sessionId: (path)  
     - parameter xAdminToken: (header)  
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: AdminSessionRevokedEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func revokeAdminSession(sessionId: String, xAdminToken: String, xRequestId: String? = nil) async throws -> AdminSessionRevokedEnvelope {
        return try await revokeAdminSessionWithRequestBuilder(sessionId: sessionId, xAdminToken: xAdminToken, xRequestId: xRequestId).execute().body
    }

    /**
     Revoke a session (ops)
     - DELETE /v2/admin/sessions/{sessionId}
     - Deletes session identity and destroys its game engine (save-on-evict).
     - parameter sessionId: (path)  
     - parameter xAdminToken: (header)  
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: RequestBuilder<AdminSessionRevokedEnvelope> 
     */
    open class func revokeAdminSessionWithRequestBuilder(sessionId: String, xAdminToken: String, xRequestId: String? = nil) -> RequestBuilder<AdminSessionRevokedEnvelope> {
        var localVariablePath = "/v2/admin/sessions/{sessionId}"
        let sessionIdPreEscape = "\(APIHelper.mapValueToPathItem(sessionId))"
        let sessionIdPostEscape = sessionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{sessionId}", with: sessionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Admin-Token": xAdminToken.encodeToJSON(),
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AdminSessionRevokedEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
