//
// HealthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class HealthAPI {

    /**
     Liveness probe — process is accepting HTTP.
     
     - returns: LivenessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getLiveness() async throws -> LivenessResponse {
        return try await getLivenessWithRequestBuilder().execute().body
    }

    /**
     Liveness probe — process is accepting HTTP.
     - GET /health
     - Always returns 200 while the JVM is up. Does **not** check JDBC/Redis. Use `/health/ready` for dependency-aware readiness. 
     - returns: RequestBuilder<LivenessResponse> 
     */
    open class func getLivenessWithRequestBuilder() -> RequestBuilder<LivenessResponse> {
        let localVariablePath = "/health"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LivenessResponse>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Readiness probe — configured auth backends reachable.
     
     - returns: ReadinessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getReadiness() async throws -> ReadinessResponse {
        return try await getReadinessWithRequestBuilder().execute().body
    }

    /**
     Readiness probe — configured auth backends reachable.
     - GET /health/ready
     - Probes JDBC, Redis, and/or file stores only when selected via `game.auth.*.store`. Returns **503** when a required dependency is DOWN. 
     - returns: RequestBuilder<ReadinessResponse> 
     */
    open class func getReadinessWithRequestBuilder() -> RequestBuilder<ReadinessResponse> {
        let localVariablePath = "/health/ready"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ReadinessResponse>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Alias for `/health/ready`.
     
     - returns: ReadinessResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getReadinessAlias() async throws -> ReadinessResponse {
        return try await getReadinessAliasWithRequestBuilder().execute().body
    }

    /**
     Alias for `/health/ready`.
     - GET /ready
     - returns: RequestBuilder<ReadinessResponse> 
     */
    open class func getReadinessAliasWithRequestBuilder() -> RequestBuilder<ReadinessResponse> {
        let localVariablePath = "/ready"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ReadinessResponse>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
