//
// V2API.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class V2API {

    /**
     Mint a guest player session and JWT.
     
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - parameter sessionRequest: (body)  (optional)
     - returns: SessionEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createSessionV2(xRequestId: String? = nil, sessionRequest: SessionRequest? = nil) async throws -> SessionEnvelope {
        return try await createSessionV2WithRequestBuilder(xRequestId: xRequestId, sessionRequest: sessionRequest).execute().body
    }

    /**
     Mint a guest player session and JWT.
     - POST /v2/session
     - Public endpoint. Returns a session id plus a Bearer token used on all subsequent `/v2/_*` calls (and as a STOMP CONNECT header for WebSocket). When multi-player isolation is enabled on the server, each session gets its own game engine. 
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - parameter sessionRequest: (body)  (optional)
     - returns: RequestBuilder<SessionEnvelope> 
     */
    open class func createSessionV2WithRequestBuilder(xRequestId: String? = nil, sessionRequest: SessionRequest? = nil) -> RequestBuilder<SessionEnvelope> {
        let localVariablePath = "/v2/session"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sessionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SessionEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Disable a content pack; returns the updated catalog.
     
     - parameter id: (path)  
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: CatalogEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func disablePackV2(id: String, xRequestId: String? = nil) async throws -> CatalogEnvelope {
        return try await disablePackV2WithRequestBuilder(id: id, xRequestId: xRequestId).execute().body
    }

    /**
     Disable a content pack; returns the updated catalog.
     - POST /v2/catalog/packs/{id}/disable
     - parameter id: (path)  
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: RequestBuilder<CatalogEnvelope> 
     */
    open class func disablePackV2WithRequestBuilder(id: String, xRequestId: String? = nil) -> RequestBuilder<CatalogEnvelope> {
        var localVariablePath = "/v2/catalog/packs/{id}/disable"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CatalogEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Enable a content pack; returns the updated catalog.
     
     - parameter id: (path)  
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: CatalogEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func enablePackV2(id: String, xRequestId: String? = nil) async throws -> CatalogEnvelope {
        return try await enablePackV2WithRequestBuilder(id: id, xRequestId: xRequestId).execute().body
    }

    /**
     Enable a content pack; returns the updated catalog.
     - POST /v2/catalog/packs/{id}/enable
     - parameter id: (path)  
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: RequestBuilder<CatalogEnvelope> 
     */
    open class func enablePackV2WithRequestBuilder(id: String, xRequestId: String? = nil) -> RequestBuilder<CatalogEnvelope> {
        var localVariablePath = "/v2/catalog/packs/{id}/enable"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CatalogEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Installed content packs and registered plugins (mod browser).
     
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: CatalogEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getCatalogV2(xRequestId: String? = nil) async throws -> CatalogEnvelope {
        return try await getCatalogV2WithRequestBuilder(xRequestId: xRequestId).execute().body
    }

    /**
     Installed content packs and registered plugins (mod browser).
     - GET /v2/catalog
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: RequestBuilder<CatalogEnvelope> 
     */
    open class func getCatalogV2WithRequestBuilder(xRequestId: String? = nil) -> RequestBuilder<CatalogEnvelope> {
        let localVariablePath = "/v2/catalog"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CatalogEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Health metrics envelope (public, no auth).
     
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: HealthEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getHealthV2(xRequestId: String? = nil) async throws -> HealthEnvelope {
        return try await getHealthV2WithRequestBuilder(xRequestId: xRequestId).execute().body
    }

    /**
     Health metrics envelope (public, no auth).
     - GET /v2/health
     - Versioned envelope with uptime, session/engine counts, memory, and the same dependency map as `/health/ready`. Excluded from JWT enforcement. 
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: RequestBuilder<HealthEnvelope> 
     */
    open class func getHealthV2WithRequestBuilder(xRequestId: String? = nil) -> RequestBuilder<HealthEnvelope> {
        let localVariablePath = "/v2/health"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<HealthEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Echo the authenticated session (no token reflected).
     
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: SessionEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSessionMeV2(xRequestId: String? = nil) async throws -> SessionEnvelope {
        return try await getSessionMeV2WithRequestBuilder(xRequestId: xRequestId).execute().body
    }

    /**
     Echo the authenticated session (no token reflected).
     - GET /v2/session/me
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: RequestBuilder<SessionEnvelope> 
     */
    open class func getSessionMeV2WithRequestBuilder(xRequestId: String? = nil) -> RequestBuilder<SessionEnvelope> {
        let localVariablePath = "/v2/session/me"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SessionEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Current game status as a typed envelope.
     
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: GameStatusEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getStatusV2(xRequestId: String? = nil) async throws -> GameStatusEnvelope {
        return try await getStatusV2WithRequestBuilder(xRequestId: xRequestId).execute().body
    }

    /**
     Current game status as a typed envelope.
     - GET /v2/status
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: RequestBuilder<GameStatusEnvelope> 
     */
    open class func getStatusV2WithRequestBuilder(xRequestId: String? = nil) -> RequestBuilder<GameStatusEnvelope> {
        let localVariablePath = "/v2/status"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GameStatusEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     List the caller's owned products.
     
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: EntitlementEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listEntitlementsV2(xRequestId: String? = nil) async throws -> EntitlementEnvelope {
        return try await listEntitlementsV2WithRequestBuilder(xRequestId: xRequestId).execute().body
    }

    /**
     List the caller's owned products.
     - GET /v2/entitlements
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: RequestBuilder<EntitlementEnvelope> 
     */
    open class func listEntitlementsV2WithRequestBuilder(xRequestId: String? = nil) -> RequestBuilder<EntitlementEnvelope> {
        let localVariablePath = "/v2/entitlements"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EntitlementEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Restore the caller's game engine from its save file.
     
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: GameStatusEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func loadGameV2(xRequestId: String? = nil) async throws -> GameStatusEnvelope {
        return try await loadGameV2WithRequestBuilder(xRequestId: xRequestId).execute().body
    }

    /**
     Restore the caller's game engine from its save file.
     - POST /v2/load
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: RequestBuilder<GameStatusEnvelope> 
     */
    open class func loadGameV2WithRequestBuilder(xRequestId: String? = nil) -> RequestBuilder<GameStatusEnvelope> {
        let localVariablePath = "/v2/load"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GameStatusEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Generate a dungeon-master narration via the active LLM provider.
     
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - parameter narrateRequest: (body)  (optional)
     - returns: NarrativeEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func narrateV2(xRequestId: String? = nil, narrateRequest: NarrateRequest? = nil) async throws -> NarrativeEnvelope {
        return try await narrateV2WithRequestBuilder(xRequestId: xRequestId, narrateRequest: narrateRequest).execute().body
    }

    /**
     Generate a dungeon-master narration via the active LLM provider.
     - POST /v2/narrate
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - parameter narrateRequest: (body)  (optional)
     - returns: RequestBuilder<NarrativeEnvelope> 
     */
    open class func narrateV2WithRequestBuilder(xRequestId: String? = nil, narrateRequest: NarrateRequest? = nil) -> RequestBuilder<NarrativeEnvelope> {
        let localVariablePath = "/v2/narrate"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: narrateRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NarrativeEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Start a fresh engine for the caller (new party/quest).
     
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: GameStatusEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func resetGameV2(xRequestId: String? = nil) async throws -> GameStatusEnvelope {
        return try await resetGameV2WithRequestBuilder(xRequestId: xRequestId).execute().body
    }

    /**
     Start a fresh engine for the caller (new party/quest).
     - POST /v2/reset
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: RequestBuilder<GameStatusEnvelope> 
     */
    open class func resetGameV2WithRequestBuilder(xRequestId: String? = nil) -> RequestBuilder<GameStatusEnvelope> {
        let localVariablePath = "/v2/reset"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GameStatusEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Persist the caller's game engine to a session-scoped save file.
     
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: GameSaveEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func saveGameV2(xRequestId: String? = nil) async throws -> GameSaveEnvelope {
        return try await saveGameV2WithRequestBuilder(xRequestId: xRequestId).execute().body
    }

    /**
     Persist the caller's game engine to a session-scoped save file.
     - POST /v2/save
     - Authenticated callers save under `game.saves.dir/{sessionId}.json`. Unauthenticated callers share the process-default engine and save as `default.json`. Each authenticated session has its own engine instance. 
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: RequestBuilder<GameSaveEnvelope> 
     */
    open class func saveGameV2WithRequestBuilder(xRequestId: String? = nil) -> RequestBuilder<GameSaveEnvelope> {
        let localVariablePath = "/v2/save"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GameSaveEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Apply a choice; returns the updated game status envelope.
     
     - parameter actionRequest: (body)  
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: GameStatusEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func submitActionV2(actionRequest: ActionRequest, xRequestId: String? = nil) async throws -> GameStatusEnvelope {
        return try await submitActionV2WithRequestBuilder(actionRequest: actionRequest, xRequestId: xRequestId).execute().body
    }

    /**
     Apply a choice; returns the updated game status envelope.
     - POST /v2/action
     - parameter actionRequest: (body)  
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: RequestBuilder<GameStatusEnvelope> 
     */
    open class func submitActionV2WithRequestBuilder(actionRequest: ActionRequest, xRequestId: String? = nil) -> RequestBuilder<GameStatusEnvelope> {
        let localVariablePath = "/v2/action"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: actionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GameStatusEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Upload and install a content-pack zip at runtime; returns the updated catalog.
     
     - parameter file: (form) Pack zip — pack.yaml plus optional items/, monsters/, strings/, quests/, campaigns/, npcs/, factions/. Pure data; code-bearing mods use the plugin loader instead. 
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - parameter replace: (query) Overwrite an already-installed pack with the same id. (optional, default to false)
     - returns: CatalogEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func uploadPackV2(file: URL, xRequestId: String? = nil, replace: Bool? = nil) async throws -> CatalogEnvelope {
        return try await uploadPackV2WithRequestBuilder(file: file, xRequestId: xRequestId, replace: replace).execute().body
    }

    /**
     Upload and install a content-pack zip at runtime; returns the updated catalog.
     - POST /v2/catalog/packs
     - parameter file: (form) Pack zip — pack.yaml plus optional items/, monsters/, strings/, quests/, campaigns/, npcs/, factions/. Pure data; code-bearing mods use the plugin loader instead. 
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - parameter replace: (query) Overwrite an already-installed pack with the same id. (optional, default to false)
     - returns: RequestBuilder<CatalogEnvelope> 
     */
    open class func uploadPackV2WithRequestBuilder(file: URL, xRequestId: String? = nil, replace: Bool? = nil) -> RequestBuilder<CatalogEnvelope> {
        let localVariablePath = "/v2/catalog/packs"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "file": file.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "replace": (wrappedValue: replace?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CatalogEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Validate a purchase receipt via its storefront and grant the entitlement.
     
     - parameter verifyReceiptRequest: (body)  
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: EntitlementEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func verifyReceiptV2(verifyReceiptRequest: VerifyReceiptRequest, xRequestId: String? = nil) async throws -> EntitlementEnvelope {
        return try await verifyReceiptV2WithRequestBuilder(verifyReceiptRequest: verifyReceiptRequest, xRequestId: xRequestId).execute().body
    }

    /**
     Validate a purchase receipt via its storefront and grant the entitlement.
     - POST /v2/entitlements/verify
     - parameter verifyReceiptRequest: (body)  
     - parameter xRequestId: (header) Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     - returns: RequestBuilder<EntitlementEnvelope> 
     */
    open class func verifyReceiptV2WithRequestBuilder(verifyReceiptRequest: VerifyReceiptRequest, xRequestId: String? = nil) -> RequestBuilder<EntitlementEnvelope> {
        let localVariablePath = "/v2/entitlements/verify"
        let localVariableURLString = AIDungeonMasterClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: verifyReceiptRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Request-Id": xRequestId?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EntitlementEnvelope>.Type = AIDungeonMasterClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
