/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminAuditEventsEnvelope,
  AdminNarrationEnvelope,
  AdminReceiptsEnvelope,
  AdminSecurityEventsEnvelope,
  AdminSessionPacksEnvelope,
  AdminSessionRevokedEnvelope,
  AdminSessionsEnvelope,
  AdminSessionsPurgedEnvelope,
  ErrorEnvelope,
} from '../models/index';
import {
    AdminAuditEventsEnvelopeFromJSON,
    AdminAuditEventsEnvelopeToJSON,
    AdminNarrationEnvelopeFromJSON,
    AdminNarrationEnvelopeToJSON,
    AdminReceiptsEnvelopeFromJSON,
    AdminReceiptsEnvelopeToJSON,
    AdminSecurityEventsEnvelopeFromJSON,
    AdminSecurityEventsEnvelopeToJSON,
    AdminSessionPacksEnvelopeFromJSON,
    AdminSessionPacksEnvelopeToJSON,
    AdminSessionRevokedEnvelopeFromJSON,
    AdminSessionRevokedEnvelopeToJSON,
    AdminSessionsEnvelopeFromJSON,
    AdminSessionsEnvelopeToJSON,
    AdminSessionsPurgedEnvelopeFromJSON,
    AdminSessionsPurgedEnvelopeToJSON,
    ErrorEnvelopeFromJSON,
    ErrorEnvelopeToJSON,
} from '../models/index';

export interface GetAdminNarrationRequest {
    xAdminToken: string;
    xRequestId?: string;
}

export interface GetAdminSessionPacksRequest {
    sessionId: string;
    xAdminToken: string;
    xRequestId?: string;
}

export interface ListAdminAuditEventsRequest {
    xAdminToken: string;
    limit?: number;
    xRequestId?: string;
}

export interface ListAdminReceiptsRequest {
    xAdminToken: string;
    limit?: number;
    productId?: string;
    storefront?: string;
    sessionId?: string;
    since?: number;
    until?: number;
    xRequestId?: string;
}

export interface ListAdminSecurityEventsRequest {
    xAdminToken: string;
    limit?: number;
    xRequestId?: string;
}

export interface ListAdminSessionsRequest {
    xAdminToken: string;
    limit?: number;
    xRequestId?: string;
}

export interface PurgeIdleAdminSessionsRequest {
    xAdminToken: string;
    idleTtlSeconds?: number;
    evictEngines?: boolean;
    xRequestId?: string;
}

export interface RevokeAdminSessionRequest {
    sessionId: string;
    xAdminToken: string;
    xRequestId?: string;
}

export interface SetAdminNarrationProviderRequest {
    id: string;
    xAdminToken: string;
    xRequestId?: string;
}

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI {

    /**
     * Active narration provider snapshot (ops)
     */
    async getAdminNarrationRaw(requestParameters: GetAdminNarrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminNarrationEnvelope>> {
        if (requestParameters['xAdminToken'] == null) {
            throw new runtime.RequiredError(
                'xAdminToken',
                'Required parameter "xAdminToken" was null or undefined when calling getAdminNarration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAdminToken'] != null) {
            headerParameters['X-Admin-Token'] = String(requestParameters['xAdminToken']);
        }

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/admin/narration`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminNarrationEnvelopeFromJSON(jsonValue));
    }

    /**
     * Active narration provider snapshot (ops)
     */
    async getAdminNarration(requestParameters: GetAdminNarrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminNarrationEnvelope> {
        const response = await this.getAdminNarrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Session pack overrides (ops)
     */
    async getAdminSessionPacksRaw(requestParameters: GetAdminSessionPacksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminSessionPacksEnvelope>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getAdminSessionPacks().'
            );
        }

        if (requestParameters['xAdminToken'] == null) {
            throw new runtime.RequiredError(
                'xAdminToken',
                'Required parameter "xAdminToken" was null or undefined when calling getAdminSessionPacks().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sessionId'] != null) {
            queryParameters['sessionId'] = requestParameters['sessionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAdminToken'] != null) {
            headerParameters['X-Admin-Token'] = String(requestParameters['xAdminToken']);
        }

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/admin/session-packs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminSessionPacksEnvelopeFromJSON(jsonValue));
    }

    /**
     * Session pack overrides (ops)
     */
    async getAdminSessionPacks(requestParameters: GetAdminSessionPacksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminSessionPacksEnvelope> {
        const response = await this.getAdminSessionPacksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Process-local ring (newest first) of `AdminAudit` outcomes for admin routes. No raw tokens — fingerprints only. 
     * Recent admin ops audit events (ops)
     */
    async listAdminAuditEventsRaw(requestParameters: ListAdminAuditEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminAuditEventsEnvelope>> {
        if (requestParameters['xAdminToken'] == null) {
            throw new runtime.RequiredError(
                'xAdminToken',
                'Required parameter "xAdminToken" was null or undefined when calling listAdminAuditEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAdminToken'] != null) {
            headerParameters['X-Admin-Token'] = String(requestParameters['xAdminToken']);
        }

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/admin/audit-events`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminAuditEventsEnvelopeFromJSON(jsonValue));
    }

    /**
     * Process-local ring (newest first) of `AdminAudit` outcomes for admin routes. No raw tokens — fingerprints only. 
     * Recent admin ops audit events (ops)
     */
    async listAdminAuditEvents(requestParameters: ListAdminAuditEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminAuditEventsEnvelope> {
        const response = await this.listAdminAuditEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List recent redeemed receipts (ops)
     */
    async listAdminReceiptsRaw(requestParameters: ListAdminReceiptsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminReceiptsEnvelope>> {
        if (requestParameters['xAdminToken'] == null) {
            throw new runtime.RequiredError(
                'xAdminToken',
                'Required parameter "xAdminToken" was null or undefined when calling listAdminReceipts().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['productId'] != null) {
            queryParameters['productId'] = requestParameters['productId'];
        }

        if (requestParameters['storefront'] != null) {
            queryParameters['storefront'] = requestParameters['storefront'];
        }

        if (requestParameters['sessionId'] != null) {
            queryParameters['sessionId'] = requestParameters['sessionId'];
        }

        if (requestParameters['since'] != null) {
            queryParameters['since'] = requestParameters['since'];
        }

        if (requestParameters['until'] != null) {
            queryParameters['until'] = requestParameters['until'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAdminToken'] != null) {
            headerParameters['X-Admin-Token'] = String(requestParameters['xAdminToken']);
        }

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/admin/receipts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminReceiptsEnvelopeFromJSON(jsonValue));
    }

    /**
     * List recent redeemed receipts (ops)
     */
    async listAdminReceipts(requestParameters: ListAdminReceiptsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminReceiptsEnvelope> {
        const response = await this.listAdminReceiptsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Process-local ring (newest first) of `SecurityAudit` outcomes (forbidden ownership, rate limits, scrape denials, etc.). No raw tokens. 
     * Recent multi-tenant security audit events (ops)
     */
    async listAdminSecurityEventsRaw(requestParameters: ListAdminSecurityEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminSecurityEventsEnvelope>> {
        if (requestParameters['xAdminToken'] == null) {
            throw new runtime.RequiredError(
                'xAdminToken',
                'Required parameter "xAdminToken" was null or undefined when calling listAdminSecurityEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAdminToken'] != null) {
            headerParameters['X-Admin-Token'] = String(requestParameters['xAdminToken']);
        }

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/admin/security-events`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminSecurityEventsEnvelopeFromJSON(jsonValue));
    }

    /**
     * Process-local ring (newest first) of `SecurityAudit` outcomes (forbidden ownership, rate limits, scrape denials, etc.). No raw tokens. 
     * Recent multi-tenant security audit events (ops)
     */
    async listAdminSecurityEvents(requestParameters: ListAdminSecurityEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminSecurityEventsEnvelope> {
        const response = await this.listAdminSecurityEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Identity only — no JWTs. Newest last-seen first.
     * List active sessions (ops)
     */
    async listAdminSessionsRaw(requestParameters: ListAdminSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminSessionsEnvelope>> {
        if (requestParameters['xAdminToken'] == null) {
            throw new runtime.RequiredError(
                'xAdminToken',
                'Required parameter "xAdminToken" was null or undefined when calling listAdminSessions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAdminToken'] != null) {
            headerParameters['X-Admin-Token'] = String(requestParameters['xAdminToken']);
        }

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/admin/sessions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminSessionsEnvelopeFromJSON(jsonValue));
    }

    /**
     * Identity only — no JWTs. Newest last-seen first.
     * List active sessions (ops)
     */
    async listAdminSessions(requestParameters: ListAdminSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminSessionsEnvelope> {
        const response = await this.listAdminSessionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes sessions idle longer than idleTtlSeconds; optionally runs engine idle eviction.
     * Purge idle sessions (ops)
     */
    async purgeIdleAdminSessionsRaw(requestParameters: PurgeIdleAdminSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminSessionsPurgedEnvelope>> {
        if (requestParameters['xAdminToken'] == null) {
            throw new runtime.RequiredError(
                'xAdminToken',
                'Required parameter "xAdminToken" was null or undefined when calling purgeIdleAdminSessions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['idleTtlSeconds'] != null) {
            queryParameters['idleTtlSeconds'] = requestParameters['idleTtlSeconds'];
        }

        if (requestParameters['evictEngines'] != null) {
            queryParameters['evictEngines'] = requestParameters['evictEngines'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAdminToken'] != null) {
            headerParameters['X-Admin-Token'] = String(requestParameters['xAdminToken']);
        }

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/admin/sessions/purge-idle`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminSessionsPurgedEnvelopeFromJSON(jsonValue));
    }

    /**
     * Removes sessions idle longer than idleTtlSeconds; optionally runs engine idle eviction.
     * Purge idle sessions (ops)
     */
    async purgeIdleAdminSessions(requestParameters: PurgeIdleAdminSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminSessionsPurgedEnvelope> {
        const response = await this.purgeIdleAdminSessionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes session identity and destroys its game engine (save-on-evict).
     * Revoke a session (ops)
     */
    async revokeAdminSessionRaw(requestParameters: RevokeAdminSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminSessionRevokedEnvelope>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling revokeAdminSession().'
            );
        }

        if (requestParameters['xAdminToken'] == null) {
            throw new runtime.RequiredError(
                'xAdminToken',
                'Required parameter "xAdminToken" was null or undefined when calling revokeAdminSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAdminToken'] != null) {
            headerParameters['X-Admin-Token'] = String(requestParameters['xAdminToken']);
        }

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/admin/sessions/{sessionId}`.replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminSessionRevokedEnvelopeFromJSON(jsonValue));
    }

    /**
     * Deletes session identity and destroys its game engine (save-on-evict).
     * Revoke a session (ops)
     */
    async revokeAdminSession(requestParameters: RevokeAdminSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminSessionRevokedEnvelope> {
        const response = await this.revokeAdminSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Calls `LLMProviderRegistry.setActive`. Multi-tenant deployments should only change this with intent — it affects all sessions on the node. 
     * Switch process-wide active LLM narration provider (ops)
     */
    async setAdminNarrationProviderRaw(requestParameters: SetAdminNarrationProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminNarrationEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setAdminNarrationProvider().'
            );
        }

        if (requestParameters['xAdminToken'] == null) {
            throw new runtime.RequiredError(
                'xAdminToken',
                'Required parameter "xAdminToken" was null or undefined when calling setAdminNarrationProvider().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAdminToken'] != null) {
            headerParameters['X-Admin-Token'] = String(requestParameters['xAdminToken']);
        }

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/admin/narration/provider`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminNarrationEnvelopeFromJSON(jsonValue));
    }

    /**
     * Calls `LLMProviderRegistry.setActive`. Multi-tenant deployments should only change this with intent — it affects all sessions on the node. 
     * Switch process-wide active LLM narration provider (ops)
     */
    async setAdminNarrationProvider(requestParameters: SetAdminNarrationProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminNarrationEnvelope> {
        const response = await this.setAdminNarrationProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
