/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminSessionRevokedEnvelope,
  AdminSessionsEnvelope,
  ErrorEnvelope,
} from '../models/index';
import {
    AdminSessionRevokedEnvelopeFromJSON,
    AdminSessionRevokedEnvelopeToJSON,
    AdminSessionsEnvelopeFromJSON,
    AdminSessionsEnvelopeToJSON,
    ErrorEnvelopeFromJSON,
    ErrorEnvelopeToJSON,
} from '../models/index';

export interface GetAdminSessionPacksRequest {
    sessionId: string;
    xAdminToken: string;
}

export interface ListAdminReceiptsRequest {
    xAdminToken: string;
    limit?: number;
    productId?: string;
    storefront?: string;
    sessionId?: string;
    since?: number;
    until?: number;
}

export interface ListAdminSessionsRequest {
    xAdminToken: string;
    limit?: number;
    xRequestId?: string;
}

export interface RevokeAdminSessionRequest {
    sessionId: string;
    xAdminToken: string;
    xRequestId?: string;
}

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI {

    /**
     * Session pack overrides (ops)
     */
    async getAdminSessionPacksRaw(requestParameters: GetAdminSessionPacksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getAdminSessionPacks().'
            );
        }

        if (requestParameters['xAdminToken'] == null) {
            throw new runtime.RequiredError(
                'xAdminToken',
                'Required parameter "xAdminToken" was null or undefined when calling getAdminSessionPacks().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sessionId'] != null) {
            queryParameters['sessionId'] = requestParameters['sessionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAdminToken'] != null) {
            headerParameters['X-Admin-Token'] = String(requestParameters['xAdminToken']);
        }

        const response = await this.request({
            path: `/v2/admin/session-packs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Session pack overrides (ops)
     */
    async getAdminSessionPacks(requestParameters: GetAdminSessionPacksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getAdminSessionPacksRaw(requestParameters, initOverrides);
    }

    /**
     * List recent redeemed receipts (ops)
     */
    async listAdminReceiptsRaw(requestParameters: ListAdminReceiptsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['xAdminToken'] == null) {
            throw new runtime.RequiredError(
                'xAdminToken',
                'Required parameter "xAdminToken" was null or undefined when calling listAdminReceipts().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['productId'] != null) {
            queryParameters['productId'] = requestParameters['productId'];
        }

        if (requestParameters['storefront'] != null) {
            queryParameters['storefront'] = requestParameters['storefront'];
        }

        if (requestParameters['sessionId'] != null) {
            queryParameters['sessionId'] = requestParameters['sessionId'];
        }

        if (requestParameters['since'] != null) {
            queryParameters['since'] = requestParameters['since'];
        }

        if (requestParameters['until'] != null) {
            queryParameters['until'] = requestParameters['until'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAdminToken'] != null) {
            headerParameters['X-Admin-Token'] = String(requestParameters['xAdminToken']);
        }

        const response = await this.request({
            path: `/v2/admin/receipts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * List recent redeemed receipts (ops)
     */
    async listAdminReceipts(requestParameters: ListAdminReceiptsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.listAdminReceiptsRaw(requestParameters, initOverrides);
    }

    /**
     * Identity only — no JWTs. Newest last-seen first.
     * List active sessions (ops)
     */
    async listAdminSessionsRaw(requestParameters: ListAdminSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminSessionsEnvelope>> {
        if (requestParameters['xAdminToken'] == null) {
            throw new runtime.RequiredError(
                'xAdminToken',
                'Required parameter "xAdminToken" was null or undefined when calling listAdminSessions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAdminToken'] != null) {
            headerParameters['X-Admin-Token'] = String(requestParameters['xAdminToken']);
        }

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/admin/sessions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminSessionsEnvelopeFromJSON(jsonValue));
    }

    /**
     * Identity only — no JWTs. Newest last-seen first.
     * List active sessions (ops)
     */
    async listAdminSessions(requestParameters: ListAdminSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminSessionsEnvelope> {
        const response = await this.listAdminSessionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes session identity and destroys its game engine (save-on-evict).
     * Revoke a session (ops)
     */
    async revokeAdminSessionRaw(requestParameters: RevokeAdminSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminSessionRevokedEnvelope>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling revokeAdminSession().'
            );
        }

        if (requestParameters['xAdminToken'] == null) {
            throw new runtime.RequiredError(
                'xAdminToken',
                'Required parameter "xAdminToken" was null or undefined when calling revokeAdminSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xAdminToken'] != null) {
            headerParameters['X-Admin-Token'] = String(requestParameters['xAdminToken']);
        }

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/admin/sessions/{sessionId}`.replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminSessionRevokedEnvelopeFromJSON(jsonValue));
    }

    /**
     * Deletes session identity and destroys its game engine (save-on-evict).
     * Revoke a session (ops)
     */
    async revokeAdminSession(requestParameters: RevokeAdminSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminSessionRevokedEnvelope> {
        const response = await this.revokeAdminSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
