/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LivenessResponse,
  ReadinessResponse,
} from '../models/index';
import {
    LivenessResponseFromJSON,
    LivenessResponseToJSON,
    ReadinessResponseFromJSON,
    ReadinessResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class HealthApi extends runtime.BaseAPI {

    /**
     * Always returns 200 while the JVM is up. Does **not** check JDBC/Redis. Use `/health/ready` for dependency-aware readiness. 
     * Liveness probe — process is accepting HTTP.
     */
    async getLivenessRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LivenessResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LivenessResponseFromJSON(jsonValue));
    }

    /**
     * Always returns 200 while the JVM is up. Does **not** check JDBC/Redis. Use `/health/ready` for dependency-aware readiness. 
     * Liveness probe — process is accepting HTTP.
     */
    async getLiveness(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LivenessResponse> {
        const response = await this.getLivenessRaw(initOverrides);
        return await response.value();
    }

    /**
     * Public plaintext metrics (`text/plain`). Prefer private network scrape. 
     * Prometheus text exposition for scrapers.
     */
    async getPrometheusMetricsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/metrics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Public plaintext metrics (`text/plain`). Prefer private network scrape. 
     * Prometheus text exposition for scrapers.
     */
    async getPrometheusMetrics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getPrometheusMetricsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Probes JDBC, Redis, and/or file stores only when selected via `game.auth.*.store`. Returns **503** when a required dependency is DOWN. 
     * Readiness probe — configured auth backends reachable.
     */
    async getReadinessRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReadinessResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/health/ready`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadinessResponseFromJSON(jsonValue));
    }

    /**
     * Probes JDBC, Redis, and/or file stores only when selected via `game.auth.*.store`. Returns **503** when a required dependency is DOWN. 
     * Readiness probe — configured auth backends reachable.
     */
    async getReadiness(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReadinessResponse> {
        const response = await this.getReadinessRaw(initOverrides);
        return await response.value();
    }

    /**
     * Alias for `/health/ready`.
     */
    async getReadinessAliasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReadinessResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ready`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadinessResponseFromJSON(jsonValue));
    }

    /**
     * Alias for `/health/ready`.
     */
    async getReadinessAlias(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReadinessResponse> {
        const response = await this.getReadinessAliasRaw(initOverrides);
        return await response.value();
    }

}
