/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ActionRequest,
  CatalogEnvelope,
  EntitlementEnvelope,
  ErrorEnvelope,
  GameStatusEnvelope,
  NarrateRequest,
  NarrativeEnvelope,
  SessionEnvelope,
  SessionRequest,
  VerifyReceiptRequest,
} from '../models/index';
import {
    ActionRequestFromJSON,
    ActionRequestToJSON,
    CatalogEnvelopeFromJSON,
    CatalogEnvelopeToJSON,
    EntitlementEnvelopeFromJSON,
    EntitlementEnvelopeToJSON,
    ErrorEnvelopeFromJSON,
    ErrorEnvelopeToJSON,
    GameStatusEnvelopeFromJSON,
    GameStatusEnvelopeToJSON,
    NarrateRequestFromJSON,
    NarrateRequestToJSON,
    NarrativeEnvelopeFromJSON,
    NarrativeEnvelopeToJSON,
    SessionEnvelopeFromJSON,
    SessionEnvelopeToJSON,
    SessionRequestFromJSON,
    SessionRequestToJSON,
    VerifyReceiptRequestFromJSON,
    VerifyReceiptRequestToJSON,
} from '../models/index';

export interface CreateSessionV2Request {
    xRequestId?: string;
    sessionRequest?: SessionRequest;
}

export interface DisablePackV2Request {
    id: string;
    xRequestId?: string;
}

export interface EnablePackV2Request {
    id: string;
    xRequestId?: string;
}

export interface GetCatalogV2Request {
    xRequestId?: string;
}

export interface GetSessionMeV2Request {
    xRequestId?: string;
}

export interface GetStatusV2Request {
    xRequestId?: string;
}

export interface ListEntitlementsV2Request {
    xRequestId?: string;
}

export interface NarrateV2Request {
    xRequestId?: string;
    narrateRequest?: NarrateRequest;
}

export interface SubmitActionV2Request {
    actionRequest: ActionRequest;
    xRequestId?: string;
}

export interface UploadPackV2Request {
    file: Blob;
    xRequestId?: string;
    replace?: boolean;
}

export interface VerifyReceiptV2Request {
    verifyReceiptRequest: VerifyReceiptRequest;
    xRequestId?: string;
}

/**
 * 
 */
export class V2Api extends runtime.BaseAPI {

    /**
     * Public endpoint. Returns a session id plus a Bearer token used on all subsequent `/v2/_*` calls (and as a STOMP CONNECT header for WebSocket). When multi-player isolation is enabled on the server, each session gets its own game engine. 
     * Mint a guest player session and JWT.
     */
    async createSessionV2Raw(requestParameters: CreateSessionV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionEnvelope>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/session`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SessionRequestToJSON(requestParameters['sessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionEnvelopeFromJSON(jsonValue));
    }

    /**
     * Public endpoint. Returns a session id plus a Bearer token used on all subsequent `/v2/_*` calls (and as a STOMP CONNECT header for WebSocket). When multi-player isolation is enabled on the server, each session gets its own game engine. 
     * Mint a guest player session and JWT.
     */
    async createSessionV2(requestParameters: CreateSessionV2Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionEnvelope> {
        const response = await this.createSessionV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Disable a content pack; returns the updated catalog.
     */
    async disablePackV2Raw(requestParameters: DisablePackV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatalogEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling disablePackV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/catalog/packs/{id}/disable`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CatalogEnvelopeFromJSON(jsonValue));
    }

    /**
     * Disable a content pack; returns the updated catalog.
     */
    async disablePackV2(requestParameters: DisablePackV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatalogEnvelope> {
        const response = await this.disablePackV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Enable a content pack; returns the updated catalog.
     */
    async enablePackV2Raw(requestParameters: EnablePackV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatalogEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling enablePackV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/catalog/packs/{id}/enable`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CatalogEnvelopeFromJSON(jsonValue));
    }

    /**
     * Enable a content pack; returns the updated catalog.
     */
    async enablePackV2(requestParameters: EnablePackV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatalogEnvelope> {
        const response = await this.enablePackV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Installed content packs and registered plugins (mod browser).
     */
    async getCatalogV2Raw(requestParameters: GetCatalogV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatalogEnvelope>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/catalog`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CatalogEnvelopeFromJSON(jsonValue));
    }

    /**
     * Installed content packs and registered plugins (mod browser).
     */
    async getCatalogV2(requestParameters: GetCatalogV2Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatalogEnvelope> {
        const response = await this.getCatalogV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Echo the authenticated session (no token reflected).
     */
    async getSessionMeV2Raw(requestParameters: GetSessionMeV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionEnvelope>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/session/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionEnvelopeFromJSON(jsonValue));
    }

    /**
     * Echo the authenticated session (no token reflected).
     */
    async getSessionMeV2(requestParameters: GetSessionMeV2Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionEnvelope> {
        const response = await this.getSessionMeV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Current game status as a typed envelope.
     */
    async getStatusV2Raw(requestParameters: GetStatusV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameStatusEnvelope>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/status`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameStatusEnvelopeFromJSON(jsonValue));
    }

    /**
     * Current game status as a typed envelope.
     */
    async getStatusV2(requestParameters: GetStatusV2Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameStatusEnvelope> {
        const response = await this.getStatusV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List the caller\'s owned products.
     */
    async listEntitlementsV2Raw(requestParameters: ListEntitlementsV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntitlementEnvelope>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/entitlements`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntitlementEnvelopeFromJSON(jsonValue));
    }

    /**
     * List the caller\'s owned products.
     */
    async listEntitlementsV2(requestParameters: ListEntitlementsV2Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntitlementEnvelope> {
        const response = await this.listEntitlementsV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate a dungeon-master narration via the active LLM provider.
     */
    async narrateV2Raw(requestParameters: NarrateV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NarrativeEnvelope>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/narrate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NarrateRequestToJSON(requestParameters['narrateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NarrativeEnvelopeFromJSON(jsonValue));
    }

    /**
     * Generate a dungeon-master narration via the active LLM provider.
     */
    async narrateV2(requestParameters: NarrateV2Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NarrativeEnvelope> {
        const response = await this.narrateV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Apply a choice; returns the updated game status envelope.
     */
    async submitActionV2Raw(requestParameters: SubmitActionV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameStatusEnvelope>> {
        if (requestParameters['actionRequest'] == null) {
            throw new runtime.RequiredError(
                'actionRequest',
                'Required parameter "actionRequest" was null or undefined when calling submitActionV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/action`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ActionRequestToJSON(requestParameters['actionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameStatusEnvelopeFromJSON(jsonValue));
    }

    /**
     * Apply a choice; returns the updated game status envelope.
     */
    async submitActionV2(requestParameters: SubmitActionV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameStatusEnvelope> {
        const response = await this.submitActionV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload and install a content-pack zip at runtime; returns the updated catalog.
     */
    async uploadPackV2Raw(requestParameters: UploadPackV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatalogEnvelope>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadPackV2().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['replace'] != null) {
            queryParameters['replace'] = requestParameters['replace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/v2/catalog/packs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CatalogEnvelopeFromJSON(jsonValue));
    }

    /**
     * Upload and install a content-pack zip at runtime; returns the updated catalog.
     */
    async uploadPackV2(requestParameters: UploadPackV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatalogEnvelope> {
        const response = await this.uploadPackV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Validate a purchase receipt via its storefront and grant the entitlement.
     */
    async verifyReceiptV2Raw(requestParameters: VerifyReceiptV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntitlementEnvelope>> {
        if (requestParameters['verifyReceiptRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyReceiptRequest',
                'Required parameter "verifyReceiptRequest" was null or undefined when calling verifyReceiptV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        const response = await this.request({
            path: `/v2/entitlements/verify`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyReceiptRequestToJSON(requestParameters['verifyReceiptRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntitlementEnvelopeFromJSON(jsonValue));
    }

    /**
     * Validate a purchase receipt via its storefront and grant the entitlement.
     */
    async verifyReceiptV2(requestParameters: VerifyReceiptV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntitlementEnvelope> {
        const response = await this.verifyReceiptV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
