/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.models.CatalogPayload
import com.xai.dungeonmaster.client.models.NarrationInfo
import com.xai.dungeonmaster.client.models.PackInfo
import com.xai.dungeonmaster.client.models.PluginSummary

class CatalogPayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CatalogPayload
        //val modelInstance = CatalogPayload()

        // to test the property `contentPacks`
        should("test contentPacks") {
            // uncomment below to test the property
            //modelInstance.contentPacks shouldBe ("TODO")
        }

        // to test the property `plugins`
        should("test plugins") {
            // uncomment below to test the property
            //modelInstance.plugins shouldBe ("TODO")
        }

        // to test the property `narration`
        should("test narration") {
            // uncomment below to test the property
            //modelInstance.narration shouldBe ("TODO")
        }

    }
}
