/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.models.DeleteSessionV2200ResponsePayload

class DeleteSessionV2200ResponsePayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeleteSessionV2200ResponsePayload
        //val modelInstance = DeleteSessionV2200ResponsePayload()

        // to test the property `loggedOut`
        should("test loggedOut") {
            // uncomment below to test the property
            //modelInstance.loggedOut shouldBe ("TODO")
        }

        // to test the property `sessionId`
        should("test sessionId") {
            // uncomment below to test the property
            //modelInstance.sessionId shouldBe ("TODO")
        }

    }
}
