/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.models.EntitlementPayload

class EntitlementPayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EntitlementPayload
        //val modelInstance = EntitlementPayload()

        // to test the property `granted`
        should("test granted") {
            // uncomment below to test the property
            //modelInstance.granted shouldBe ("TODO")
        }

        // to test the property `productId`
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `storefront`
        should("test storefront") {
            // uncomment below to test the property
            //modelInstance.storefront shouldBe ("TODO")
        }

        // to test the property `reason`
        should("test reason") {
            // uncomment below to test the property
            //modelInstance.reason shouldBe ("TODO")
        }

        // to test the property `owned`
        should("test owned") {
            // uncomment below to test the property
            //modelInstance.owned shouldBe ("TODO")
        }

    }
}
