/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.models.Envelope

class EnvelopeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Envelope
        //val modelInstance = Envelope()

        // to test the property `type` - Payload discriminator (game_status, narrative_update, error).
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `version` - Schema version of the payload contract.
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `payload` - Typed body; shape depends on `type`.
        should("test payload") {
            // uncomment below to test the property
            //modelInstance.payload shouldBe ("TODO")
        }

        // to test the property `requestId` - Correlation id (echoed from X-Request-Id or generated).
        should("test requestId") {
            // uncomment below to test the property
            //modelInstance.requestId shouldBe ("TODO")
        }

    }
}
