/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.models.GameSaveEnvelopeAllOfPayload

class GameSaveEnvelopeAllOfPayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GameSaveEnvelopeAllOfPayload
        //val modelInstance = GameSaveEnvelopeAllOfPayload()

        // to test the property `saved`
        should("test saved") {
            // uncomment below to test the property
            //modelInstance.saved shouldBe ("TODO")
        }

        // to test the property `path`
        should("test path") {
            // uncomment below to test the property
            //modelInstance.path shouldBe ("TODO")
        }

        // to test the property `sessionScoped`
        should("test sessionScoped") {
            // uncomment below to test the property
            //modelInstance.sessionScoped shouldBe ("TODO")
        }

    }
}
