/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.models.GameStatusV2
import com.xai.dungeonmaster.client.models.MemberState

class GameStatusV2Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of GameStatusV2
        //val modelInstance = GameStatusV2()

        // to test the property `party`
        should("test party") {
            // uncomment below to test the property
            //modelInstance.party shouldBe ("TODO")
        }

        // to test the property `chaosLevel`
        should("test chaosLevel") {
            // uncomment below to test the property
            //modelInstance.chaosLevel shouldBe ("TODO")
        }

        // to test the property `combatActive`
        should("test combatActive") {
            // uncomment below to test the property
            //modelInstance.combatActive shouldBe ("TODO")
        }

        // to test the property `availableChoices`
        should("test availableChoices") {
            // uncomment below to test the property
            //modelInstance.availableChoices shouldBe ("TODO")
        }

        // to test the property `recentHistory`
        should("test recentHistory") {
            // uncomment below to test the property
            //modelInstance.recentHistory shouldBe ("TODO")
        }

    }
}
