/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.models.LivenessResponse

class LivenessResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LivenessResponse
        //val modelInstance = LivenessResponse()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `probe`
        should("test probe") {
            // uncomment below to test the property
            //modelInstance.probe shouldBe ("TODO")
        }

    }
}
