/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.models.MarketplacePayload
import com.xai.dungeonmaster.client.models.MarketplaceListing

class MarketplacePayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MarketplacePayload
        //val modelInstance = MarketplacePayload()

        // to test the property `root`
        should("test root") {
            // uncomment below to test the property
            //modelInstance.root shouldBe ("TODO")
        }

        // to test the property `remoteIndexUrl`
        should("test remoteIndexUrl") {
            // uncomment below to test the property
            //modelInstance.remoteIndexUrl shouldBe ("TODO")
        }

        // to test the property `remoteOk`
        should("test remoteOk") {
            // uncomment below to test the property
            //modelInstance.remoteOk shouldBe ("TODO")
        }

        // to test the property `remoteError`
        should("test remoteError") {
            // uncomment below to test the property
            //modelInstance.remoteError shouldBe ("TODO")
        }

        // to test the property `available`
        should("test available") {
            // uncomment below to test the property
            //modelInstance.available shouldBe ("TODO")
        }

        // to test the property `installed`
        should("test installed") {
            // uncomment below to test the property
            //modelInstance.installed shouldBe ("TODO")
        }

        // to test the property `packs`
        should("test packs") {
            // uncomment below to test the property
            //modelInstance.packs shouldBe ("TODO")
        }

    }
}
