/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.models.MarketplaceListing

class MarketplaceListingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MarketplaceListing
        //val modelInstance = MarketplaceListing()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `version`
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `installed`
        should("test installed") {
            // uncomment below to test the property
            //modelInstance.installed shouldBe ("TODO")
        }

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

        // to test the property `source`
        should("test source") {
            // uncomment below to test the property
            //modelInstance.source shouldBe ("TODO")
        }

        // to test the property `minEngineVersion`
        should("test minEngineVersion") {
            // uncomment below to test the property
            //modelInstance.minEngineVersion shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `sourcePath`
        should("test sourcePath") {
            // uncomment below to test the property
            //modelInstance.sourcePath shouldBe ("TODO")
        }

        // to test the property `downloadUrl`
        should("test downloadUrl") {
            // uncomment below to test the property
            //modelInstance.downloadUrl shouldBe ("TODO")
        }

        // to test the property `sha256`
        should("test sha256") {
            // uncomment below to test the property
            //modelInstance.sha256 shouldBe ("TODO")
        }

    }
}
