/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.models.MemberState

class MemberStateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MemberState
        //val modelInstance = MemberState()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `role`
        should("test role") {
            // uncomment below to test the property
            //modelInstance.role shouldBe ("TODO")
        }

        // to test the property `level`
        should("test level") {
            // uncomment below to test the property
            //modelInstance.level shouldBe ("TODO")
        }

        // to test the property `hp`
        should("test hp") {
            // uncomment below to test the property
            //modelInstance.hp shouldBe ("TODO")
        }

        // to test the property `maxHp`
        should("test maxHp") {
            // uncomment below to test the property
            //modelInstance.maxHp shouldBe ("TODO")
        }

        // to test the property `mana`
        should("test mana") {
            // uncomment below to test the property
            //modelInstance.mana shouldBe ("TODO")
        }

        // to test the property `maxMana`
        should("test maxMana") {
            // uncomment below to test the property
            //modelInstance.maxMana shouldBe ("TODO")
        }

        // to test the property `armorClass`
        should("test armorClass") {
            // uncomment below to test the property
            //modelInstance.armorClass shouldBe ("TODO")
        }

        // to test the property `alive`
        should("test alive") {
            // uncomment below to test the property
            //modelInstance.alive shouldBe ("TODO")
        }

        // to test the property `ascendant`
        should("test ascendant") {
            // uncomment below to test the property
            //modelInstance.ascendant shouldBe ("TODO")
        }

        // to test the property `statuses`
        should("test statuses") {
            // uncomment below to test the property
            //modelInstance.statuses shouldBe ("TODO")
        }

    }
}
