/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.models.PluginSummary

class PluginSummaryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PluginSummary
        //val modelInstance = PluginSummary()

        // to test the property `spellEffects`
        should("test spellEffects") {
            // uncomment below to test the property
            //modelInstance.spellEffects shouldBe ("TODO")
        }

        // to test the property `itemEffects`
        should("test itemEffects") {
            // uncomment below to test the property
            //modelInstance.itemEffects shouldBe ("TODO")
        }

        // to test the property `encounterBiomes`
        should("test encounterBiomes") {
            // uncomment below to test the property
            //modelInstance.encounterBiomes shouldBe ("TODO")
        }

        // to test the property `lootBiomes`
        should("test lootBiomes") {
            // uncomment below to test the property
            //modelInstance.lootBiomes shouldBe ("TODO")
        }

        // to test the property `questScripts`
        should("test questScripts") {
            // uncomment below to test the property
            //modelInstance.questScripts shouldBe ("TODO")
        }

        // to test the property `storefronts`
        should("test storefronts") {
            // uncomment below to test the property
            //modelInstance.storefronts shouldBe ("TODO")
        }

        // to test the property `llmProviders`
        should("test llmProviders") {
            // uncomment below to test the property
            //modelInstance.llmProviders shouldBe ("TODO")
        }

    }
}
