/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.models.QuestInfo

class QuestInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QuestInfo
        //val modelInstance = QuestInfo()

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `completed`
        should("test completed") {
            // uncomment below to test the property
            //modelInstance.completed shouldBe ("TODO")
        }

        // to test the property `failed`
        should("test failed") {
            // uncomment below to test the property
            //modelInstance.failed shouldBe ("TODO")
        }

        // to test the property `progress` - Scene progress in [0,1].
        should("test progress") {
            // uncomment below to test the property
            //modelInstance.progress shouldBe ("TODO")
        }

    }
}
