/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CatalogPayload } from './CatalogPayload';
import {
    CatalogPayloadFromJSON,
    CatalogPayloadFromJSONTyped,
    CatalogPayloadToJSON,
} from './CatalogPayload';

/**
 * 
 * @export
 * @interface CatalogEnvelope
 */
export interface CatalogEnvelope {
    /**
     * 
     * @type {string}
     * @memberof CatalogEnvelope
     */
    type: string;
    /**
     * Schema version of the payload contract.
     * @type {number}
     * @memberof CatalogEnvelope
     */
    version: number;
    /**
     * 
     * @type {CatalogPayload}
     * @memberof CatalogEnvelope
     */
    payload: CatalogPayload;
    /**
     * Correlation id (echoed from X-Request-Id or generated).
     * @type {string}
     * @memberof CatalogEnvelope
     */
    requestId: string;
}

/**
 * Check if a given object implements the CatalogEnvelope interface.
 */
export function instanceOfCatalogEnvelope(value: object): value is CatalogEnvelope {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function CatalogEnvelopeFromJSON(json: any): CatalogEnvelope {
    return CatalogEnvelopeFromJSONTyped(json, false);
}

export function CatalogEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'version': json['version'],
        'payload': CatalogPayloadFromJSON(json['payload']),
        'requestId': json['requestId'],
    };
}

export function CatalogEnvelopeToJSON(value?: CatalogEnvelope | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'version': value['version'],
        'payload': CatalogPayloadToJSON(value['payload']),
        'requestId': value['requestId'],
    };
}

