/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteSessionV2200ResponsePayload
 */
export interface DeleteSessionV2200ResponsePayload {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteSessionV2200ResponsePayload
     */
    loggedOut?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeleteSessionV2200ResponsePayload
     */
    sessionId?: string;
}

/**
 * Check if a given object implements the DeleteSessionV2200ResponsePayload interface.
 */
export function instanceOfDeleteSessionV2200ResponsePayload(value: object): value is DeleteSessionV2200ResponsePayload {
    return true;
}

export function DeleteSessionV2200ResponsePayloadFromJSON(json: any): DeleteSessionV2200ResponsePayload {
    return DeleteSessionV2200ResponsePayloadFromJSONTyped(json, false);
}

export function DeleteSessionV2200ResponsePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteSessionV2200ResponsePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'loggedOut': json['loggedOut'] == null ? undefined : json['loggedOut'],
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
    };
}

export function DeleteSessionV2200ResponsePayloadToJSON(value?: DeleteSessionV2200ResponsePayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'loggedOut': value['loggedOut'],
        'sessionId': value['sessionId'],
    };
}

