/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Base transport envelope. Concrete responses specialize `payload`.
 * @export
 * @interface Envelope
 */
export interface Envelope {
    /**
     * Payload discriminator (game_status, narrative_update, error).
     * @type {string}
     * @memberof Envelope
     */
    type: string;
    /**
     * Schema version of the payload contract.
     * @type {number}
     * @memberof Envelope
     */
    version: number;
    /**
     * Typed body; shape depends on `type`.
     * @type {object}
     * @memberof Envelope
     */
    payload: object;
    /**
     * Correlation id (echoed from X-Request-Id or generated).
     * @type {string}
     * @memberof Envelope
     */
    requestId: string;
}

/**
 * Check if a given object implements the Envelope interface.
 */
export function instanceOfEnvelope(value: object): value is Envelope {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function EnvelopeFromJSON(json: any): Envelope {
    return EnvelopeFromJSONTyped(json, false);
}

export function EnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Envelope {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'version': json['version'],
        'payload': json['payload'],
        'requestId': json['requestId'],
    };
}

export function EnvelopeToJSON(value?: Envelope | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'version': value['version'],
        'payload': value['payload'],
        'requestId': value['requestId'],
    };
}

