/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorPayload
 */
export interface ErrorPayload {
    /**
     * 
     * @type {string}
     * @memberof ErrorPayload
     */
    message?: string;
}

/**
 * Check if a given object implements the ErrorPayload interface.
 */
export function instanceOfErrorPayload(value: object): value is ErrorPayload {
    return true;
}

export function ErrorPayloadFromJSON(json: any): ErrorPayload {
    return ErrorPayloadFromJSONTyped(json, false);
}

export function ErrorPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ErrorPayloadToJSON(value?: ErrorPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

