/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameStatusV2 } from './GameStatusV2';
import {
    GameStatusV2FromJSON,
    GameStatusV2FromJSONTyped,
    GameStatusV2ToJSON,
} from './GameStatusV2';

/**
 * 
 * @export
 * @interface GameStatusEnvelope
 */
export interface GameStatusEnvelope {
    /**
     * 
     * @type {string}
     * @memberof GameStatusEnvelope
     */
    type: string;
    /**
     * Schema version of the payload contract.
     * @type {number}
     * @memberof GameStatusEnvelope
     */
    version: number;
    /**
     * 
     * @type {GameStatusV2}
     * @memberof GameStatusEnvelope
     */
    payload: GameStatusV2;
    /**
     * Correlation id (echoed from X-Request-Id or generated).
     * @type {string}
     * @memberof GameStatusEnvelope
     */
    requestId: string;
}

/**
 * Check if a given object implements the GameStatusEnvelope interface.
 */
export function instanceOfGameStatusEnvelope(value: object): value is GameStatusEnvelope {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function GameStatusEnvelopeFromJSON(json: any): GameStatusEnvelope {
    return GameStatusEnvelopeFromJSONTyped(json, false);
}

export function GameStatusEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStatusEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'version': json['version'],
        'payload': GameStatusV2FromJSON(json['payload']),
        'requestId': json['requestId'],
    };
}

export function GameStatusEnvelopeToJSON(value?: GameStatusEnvelope | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'version': value['version'],
        'payload': GameStatusV2ToJSON(value['payload']),
        'requestId': value['requestId'],
    };
}

