/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HealthPayload } from './HealthPayload';
import {
    HealthPayloadFromJSON,
    HealthPayloadFromJSONTyped,
    HealthPayloadToJSON,
} from './HealthPayload';

/**
 * 
 * @export
 * @interface HealthEnvelope
 */
export interface HealthEnvelope {
    /**
     * 
     * @type {string}
     * @memberof HealthEnvelope
     */
    type: HealthEnvelopeTypeEnum;
    /**
     * Schema version of the payload contract.
     * @type {number}
     * @memberof HealthEnvelope
     */
    version: number;
    /**
     * 
     * @type {HealthPayload}
     * @memberof HealthEnvelope
     */
    payload: HealthPayload;
    /**
     * Correlation id (echoed from X-Request-Id or generated).
     * @type {string}
     * @memberof HealthEnvelope
     */
    requestId: string;
}


/**
 * @export
 */
export const HealthEnvelopeTypeEnum = {
    Health: 'health'
} as const;
export type HealthEnvelopeTypeEnum = typeof HealthEnvelopeTypeEnum[keyof typeof HealthEnvelopeTypeEnum];


/**
 * Check if a given object implements the HealthEnvelope interface.
 */
export function instanceOfHealthEnvelope(value: object): value is HealthEnvelope {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function HealthEnvelopeFromJSON(json: any): HealthEnvelope {
    return HealthEnvelopeFromJSONTyped(json, false);
}

export function HealthEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'version': json['version'],
        'payload': HealthPayloadFromJSON(json['payload']),
        'requestId': json['requestId'],
    };
}

export function HealthEnvelopeToJSON(value?: HealthEnvelope | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'version': value['version'],
        'payload': HealthPayloadToJSON(value['payload']),
        'requestId': value['requestId'],
    };
}

