/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LivenessResponse
 */
export interface LivenessResponse {
    /**
     * 
     * @type {string}
     * @memberof LivenessResponse
     */
    status: LivenessResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof LivenessResponse
     */
    probe: LivenessResponseProbeEnum;
}


/**
 * @export
 */
export const LivenessResponseStatusEnum = {
    Up: 'UP'
} as const;
export type LivenessResponseStatusEnum = typeof LivenessResponseStatusEnum[keyof typeof LivenessResponseStatusEnum];

/**
 * @export
 */
export const LivenessResponseProbeEnum = {
    Liveness: 'liveness'
} as const;
export type LivenessResponseProbeEnum = typeof LivenessResponseProbeEnum[keyof typeof LivenessResponseProbeEnum];


/**
 * Check if a given object implements the LivenessResponse interface.
 */
export function instanceOfLivenessResponse(value: object): value is LivenessResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('probe' in value) || value['probe'] === undefined) return false;
    return true;
}

export function LivenessResponseFromJSON(json: any): LivenessResponse {
    return LivenessResponseFromJSONTyped(json, false);
}

export function LivenessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LivenessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'probe': json['probe'],
    };
}

export function LivenessResponseToJSON(value?: LivenessResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'probe': value['probe'],
    };
}

