/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarketplaceInstallJob
 */
export interface MarketplaceInstallJob {
    /**
     * 
     * @type {string}
     * @memberof MarketplaceInstallJob
     */
    jobId: string;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceInstallJob
     */
    packId: string;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceInstallJob
     */
    phase: MarketplaceInstallJobPhaseEnum;
    /**
     * 
     * @type {number}
     * @memberof MarketplaceInstallJob
     */
    bytesRead?: number;
    /**
     * 
     * @type {number}
     * @memberof MarketplaceInstallJob
     */
    bytesTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof MarketplaceInstallJob
     */
    percent: number;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceInstallJob
     */
    message?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MarketplaceInstallJob
     */
    cancelRequested?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceInstallJob
     */
    error?: string | null;
}


/**
 * @export
 */
export const MarketplaceInstallJobPhaseEnum = {
    Queued: 'QUEUED',
    Downloading: 'DOWNLOADING',
    Verifying: 'VERIFYING',
    Installing: 'INSTALLING',
    Done: 'DONE',
    Failed: 'FAILED',
    Cancelled: 'CANCELLED'
} as const;
export type MarketplaceInstallJobPhaseEnum = typeof MarketplaceInstallJobPhaseEnum[keyof typeof MarketplaceInstallJobPhaseEnum];


/**
 * Check if a given object implements the MarketplaceInstallJob interface.
 */
export function instanceOfMarketplaceInstallJob(value: object): value is MarketplaceInstallJob {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('packId' in value) || value['packId'] === undefined) return false;
    if (!('phase' in value) || value['phase'] === undefined) return false;
    if (!('percent' in value) || value['percent'] === undefined) return false;
    return true;
}

export function MarketplaceInstallJobFromJSON(json: any): MarketplaceInstallJob {
    return MarketplaceInstallJobFromJSONTyped(json, false);
}

export function MarketplaceInstallJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketplaceInstallJob {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'],
        'packId': json['packId'],
        'phase': json['phase'],
        'bytesRead': json['bytesRead'] == null ? undefined : json['bytesRead'],
        'bytesTotal': json['bytesTotal'] == null ? undefined : json['bytesTotal'],
        'percent': json['percent'],
        'message': json['message'] == null ? undefined : json['message'],
        'cancelRequested': json['cancelRequested'] == null ? undefined : json['cancelRequested'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function MarketplaceInstallJobToJSON(value?: MarketplaceInstallJob | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jobId': value['jobId'],
        'packId': value['packId'],
        'phase': value['phase'],
        'bytesRead': value['bytesRead'],
        'bytesTotal': value['bytesTotal'],
        'percent': value['percent'],
        'message': value['message'],
        'cancelRequested': value['cancelRequested'],
        'error': value['error'],
    };
}

