/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketplaceListing } from './MarketplaceListing';
import {
    MarketplaceListingFromJSON,
    MarketplaceListingFromJSONTyped,
    MarketplaceListingToJSON,
} from './MarketplaceListing';

/**
 * 
 * @export
 * @interface MarketplacePackEnvelope
 */
export interface MarketplacePackEnvelope {
    /**
     * 
     * @type {string}
     * @memberof MarketplacePackEnvelope
     */
    type: MarketplacePackEnvelopeTypeEnum;
    /**
     * Schema version of the payload contract.
     * @type {number}
     * @memberof MarketplacePackEnvelope
     */
    version: number;
    /**
     * 
     * @type {MarketplaceListing}
     * @memberof MarketplacePackEnvelope
     */
    payload: MarketplaceListing;
    /**
     * Correlation id (echoed from X-Request-Id or generated).
     * @type {string}
     * @memberof MarketplacePackEnvelope
     */
    requestId: string;
}


/**
 * @export
 */
export const MarketplacePackEnvelopeTypeEnum = {
    MarketplacePack: 'marketplace_pack'
} as const;
export type MarketplacePackEnvelopeTypeEnum = typeof MarketplacePackEnvelopeTypeEnum[keyof typeof MarketplacePackEnvelopeTypeEnum];


/**
 * Check if a given object implements the MarketplacePackEnvelope interface.
 */
export function instanceOfMarketplacePackEnvelope(value: object): value is MarketplacePackEnvelope {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function MarketplacePackEnvelopeFromJSON(json: any): MarketplacePackEnvelope {
    return MarketplacePackEnvelopeFromJSONTyped(json, false);
}

export function MarketplacePackEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketplacePackEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'version': json['version'],
        'payload': MarketplaceListingFromJSON(json['payload']),
        'requestId': json['requestId'],
    };
}

export function MarketplacePackEnvelopeToJSON(value?: MarketplacePackEnvelope | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'version': value['version'],
        'payload': MarketplaceListingToJSON(value['payload']),
        'requestId': value['requestId'],
    };
}

