/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag.  Public **health** probes (`/health`, `/health/ready`, `/v2/health`) need no auth for lean status. Session counts, dependency maps, and memory detail require `X-Metrics-Token` or `X-Admin-Token`. `GET /metrics` requires the scrape token when configured (always in production). 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketplaceInstallResult } from './MarketplaceInstallResult';
import {
    MarketplaceInstallResultFromJSON,
    MarketplaceInstallResultFromJSONTyped,
    MarketplaceInstallResultToJSON,
} from './MarketplaceInstallResult';

/**
 * 
 * @export
 * @interface MarketplaceInstallEnvelope
 */
export interface MarketplaceInstallEnvelope {
    /**
     * 
     * @type {string}
     * @memberof MarketplaceInstallEnvelope
     */
    type: MarketplaceInstallEnvelopeTypeEnum;
    /**
     * Schema version of the payload contract.
     * @type {number}
     * @memberof MarketplaceInstallEnvelope
     */
    version: number;
    /**
     * 
     * @type {MarketplaceInstallResult}
     * @memberof MarketplaceInstallEnvelope
     */
    payload: MarketplaceInstallResult;
    /**
     * Correlation id (echoed from X-Request-Id or generated).
     * @type {string}
     * @memberof MarketplaceInstallEnvelope
     */
    requestId: string;
}


/**
 * @export
 */
export const MarketplaceInstallEnvelopeTypeEnum = {
    MarketplaceInstall: 'marketplace_install'
} as const;
export type MarketplaceInstallEnvelopeTypeEnum = typeof MarketplaceInstallEnvelopeTypeEnum[keyof typeof MarketplaceInstallEnvelopeTypeEnum];


/**
 * Check if a given object implements the MarketplaceInstallEnvelope interface.
 */
export function instanceOfMarketplaceInstallEnvelope(value: object): value is MarketplaceInstallEnvelope {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function MarketplaceInstallEnvelopeFromJSON(json: any): MarketplaceInstallEnvelope {
    return MarketplaceInstallEnvelopeFromJSONTyped(json, false);
}

export function MarketplaceInstallEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketplaceInstallEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'version': json['version'],
        'payload': MarketplaceInstallResultFromJSON(json['payload']),
        'requestId': json['requestId'],
    };
}

export function MarketplaceInstallEnvelopeToJSON(value?: MarketplaceInstallEnvelope | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'version': value['version'],
        'payload': MarketplaceInstallResultToJSON(value['payload']),
        'requestId': value['requestId'],
    };
}

