/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NarrativePayload
 */
export interface NarrativePayload {
    /**
     * 
     * @type {string}
     * @memberof NarrativePayload
     */
    text?: string;
    /**
     * Active provider id, e.g. local-stub.
     * @type {string}
     * @memberof NarrativePayload
     */
    provider?: string;
    /**
     * 
     * @type {number}
     * @memberof NarrativePayload
     */
    tokensUsed?: number;
    /**
     * True when a guardrail/fallback response was returned.
     * @type {boolean}
     * @memberof NarrativePayload
     */
    fallback?: boolean;
}

/**
 * Check if a given object implements the NarrativePayload interface.
 */
export function instanceOfNarrativePayload(value: object): value is NarrativePayload {
    return true;
}

export function NarrativePayloadFromJSON(json: any): NarrativePayload {
    return NarrativePayloadFromJSONTyped(json, false);
}

export function NarrativePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): NarrativePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'tokensUsed': json['tokensUsed'] == null ? undefined : json['tokensUsed'],
        'fallback': json['fallback'] == null ? undefined : json['fallback'],
    };
}

export function NarrativePayloadToJSON(value?: NarrativePayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'text': value['text'],
        'provider': value['provider'],
        'tokensUsed': value['tokensUsed'],
        'fallback': value['fallback'],
    };
}

