/* tslint:disable */
/* eslint-disable */
/**
 * AI Dungeon Master API
 * HTTP API for the AI Dungeon Master engine.  The **v2** API (`/v2/_*`) wraps every response in a typed, versioned `Envelope` — `{ type, version, payload, requestId }` — so native clients get a stable, self-describing contract. The legacy `/api/game/_*` endpoints remain for existing clients and are documented under the `legacy` tag. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One installed content pack.
 * @export
 * @interface PackInfo
 */
export interface PackInfo {
    /**
     * 
     * @type {string}
     * @memberof PackInfo
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PackInfo
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof PackInfo
     */
    version?: string;
    /**
     * 
     * @type {number}
     * @memberof PackInfo
     */
    monsters?: number;
    /**
     * 
     * @type {number}
     * @memberof PackInfo
     */
    items?: number;
}

/**
 * Check if a given object implements the PackInfo interface.
 */
export function instanceOfPackInfo(value: object): value is PackInfo {
    return true;
}

export function PackInfoFromJSON(json: any): PackInfo {
    return PackInfoFromJSONTyped(json, false);
}

export function PackInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'version': json['version'] == null ? undefined : json['version'],
        'monsters': json['monsters'] == null ? undefined : json['monsters'],
        'items': json['items'] == null ? undefined : json['items'],
    };
}

export function PackInfoToJSON(value?: PackInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'displayName': value['displayName'],
        'version': value['version'],
        'monsters': value['monsters'],
        'items': value['items'],
    };
}

