/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.apis

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import com.xai.dungeonmaster.client.models.LivenessResponse
import com.xai.dungeonmaster.client.models.ReadinessResponse

import com.squareup.moshi.Json

import com.xai.dungeonmaster.client.infrastructure.ApiClient
import com.xai.dungeonmaster.client.infrastructure.ApiResponse
import com.xai.dungeonmaster.client.infrastructure.ClientException
import com.xai.dungeonmaster.client.infrastructure.ClientError
import com.xai.dungeonmaster.client.infrastructure.ServerException
import com.xai.dungeonmaster.client.infrastructure.ServerError
import com.xai.dungeonmaster.client.infrastructure.MultiValueMap
import com.xai.dungeonmaster.client.infrastructure.PartConfig
import com.xai.dungeonmaster.client.infrastructure.RequestConfig
import com.xai.dungeonmaster.client.infrastructure.RequestMethod
import com.xai.dungeonmaster.client.infrastructure.ResponseType
import com.xai.dungeonmaster.client.infrastructure.Success
import com.xai.dungeonmaster.client.infrastructure.toMultiValue

class HealthApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:8080")
        }
    }

    /**
     * Liveness probe — process is accepting HTTP.
     * Always returns 200 while the JVM is up. Does **not** check JDBC/Redis. Use &#x60;/health/ready&#x60; for dependency-aware readiness. 
     * @return LivenessResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getLiveness() : LivenessResponse {
        val localVarResponse = getLivenessWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LivenessResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Liveness probe — process is accepting HTTP.
     * Always returns 200 while the JVM is up. Does **not** check JDBC/Redis. Use &#x60;/health/ready&#x60; for dependency-aware readiness. 
     * @return ApiResponse<LivenessResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getLivenessWithHttpInfo() : ApiResponse<LivenessResponse?> {
        val localVariableConfig = getLivenessRequestConfig()

        return request<Unit, LivenessResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getLiveness
     *
     * @return RequestConfig
     */
    fun getLivenessRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/health",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Readiness probe — configured auth backends reachable.
     * Probes JDBC, Redis, and/or file stores only when selected via &#x60;game.auth.*.store&#x60;. Returns **503** when a required dependency is DOWN. 
     * @return ReadinessResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getReadiness() : ReadinessResponse {
        val localVarResponse = getReadinessWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ReadinessResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Readiness probe — configured auth backends reachable.
     * Probes JDBC, Redis, and/or file stores only when selected via &#x60;game.auth.*.store&#x60;. Returns **503** when a required dependency is DOWN. 
     * @return ApiResponse<ReadinessResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getReadinessWithHttpInfo() : ApiResponse<ReadinessResponse?> {
        val localVariableConfig = getReadinessRequestConfig()

        return request<Unit, ReadinessResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getReadiness
     *
     * @return RequestConfig
     */
    fun getReadinessRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/health/ready",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Alias for &#x60;/health/ready&#x60;.
     * 
     * @return ReadinessResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getReadinessAlias() : ReadinessResponse {
        val localVarResponse = getReadinessAliasWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ReadinessResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Alias for &#x60;/health/ready&#x60;.
     * 
     * @return ApiResponse<ReadinessResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getReadinessAliasWithHttpInfo() : ApiResponse<ReadinessResponse?> {
        val localVariableConfig = getReadinessAliasRequestConfig()

        return request<Unit, ReadinessResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getReadinessAlias
     *
     * @return RequestConfig
     */
    fun getReadinessAliasRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/ready",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
