/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.apis

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import com.xai.dungeonmaster.client.models.ActionRequest
import com.xai.dungeonmaster.client.models.CatalogEnvelope
import com.xai.dungeonmaster.client.models.DeleteSessionV2200Response
import com.xai.dungeonmaster.client.models.EntitlementEnvelope
import com.xai.dungeonmaster.client.models.ErrorEnvelope
import com.xai.dungeonmaster.client.models.GameSaveEnvelope
import com.xai.dungeonmaster.client.models.GameStatusEnvelope
import com.xai.dungeonmaster.client.models.HealthEnvelope
import com.xai.dungeonmaster.client.models.MarketplaceEnvelope
import com.xai.dungeonmaster.client.models.MarketplaceInstallEnvelope
import com.xai.dungeonmaster.client.models.MarketplaceInstallJobEnvelope
import com.xai.dungeonmaster.client.models.MarketplacePackEnvelope
import com.xai.dungeonmaster.client.models.NarrateRequest
import com.xai.dungeonmaster.client.models.NarrativeEnvelope
import com.xai.dungeonmaster.client.models.SessionEnvelope
import com.xai.dungeonmaster.client.models.SessionRequest
import com.xai.dungeonmaster.client.models.VerifyReceiptRequest

import com.squareup.moshi.Json

import com.xai.dungeonmaster.client.infrastructure.ApiClient
import com.xai.dungeonmaster.client.infrastructure.ApiResponse
import com.xai.dungeonmaster.client.infrastructure.ClientException
import com.xai.dungeonmaster.client.infrastructure.ClientError
import com.xai.dungeonmaster.client.infrastructure.ServerException
import com.xai.dungeonmaster.client.infrastructure.ServerError
import com.xai.dungeonmaster.client.infrastructure.MultiValueMap
import com.xai.dungeonmaster.client.infrastructure.PartConfig
import com.xai.dungeonmaster.client.infrastructure.RequestConfig
import com.xai.dungeonmaster.client.infrastructure.RequestMethod
import com.xai.dungeonmaster.client.infrastructure.ResponseType
import com.xai.dungeonmaster.client.infrastructure.Success
import com.xai.dungeonmaster.client.infrastructure.toMultiValue

class V2Api(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:8080")
        }
    }

    /**
     * Cancel an async marketplace install.
     * Same ownership ACL as poll — only the owning session may cancel. 
     * @param jobId 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return MarketplaceInstallJobEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun cancelMarketplaceInstallJobV2(jobId: kotlin.String, xRequestId: kotlin.String? = null) : MarketplaceInstallJobEnvelope {
        val localVarResponse = cancelMarketplaceInstallJobV2WithHttpInfo(jobId = jobId, xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MarketplaceInstallJobEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Cancel an async marketplace install.
     * Same ownership ACL as poll — only the owning session may cancel. 
     * @param jobId 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<MarketplaceInstallJobEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun cancelMarketplaceInstallJobV2WithHttpInfo(jobId: kotlin.String, xRequestId: kotlin.String?) : ApiResponse<MarketplaceInstallJobEnvelope?> {
        val localVariableConfig = cancelMarketplaceInstallJobV2RequestConfig(jobId = jobId, xRequestId = xRequestId)

        return request<Unit, MarketplaceInstallJobEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation cancelMarketplaceInstallJobV2
     *
     * @param jobId 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun cancelMarketplaceInstallJobV2RequestConfig(jobId: kotlin.String, xRequestId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v2/marketplace/jobs/{jobId}".replace("{"+"jobId"+"}", encodeURIComponent(jobId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Mint a guest player session and JWT.
     * Public endpoint. Returns a session id plus a Bearer token used on all subsequent &#x60;/v2/_*&#x60; calls (and as a STOMP CONNECT header for WebSocket). When multi-player isolation is enabled on the server, each session gets its own game engine. 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param sessionRequest  (optional)
     * @return SessionEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createSessionV2(xRequestId: kotlin.String? = null, sessionRequest: SessionRequest? = null) : SessionEnvelope {
        val localVarResponse = createSessionV2WithHttpInfo(xRequestId = xRequestId, sessionRequest = sessionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SessionEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Mint a guest player session and JWT.
     * Public endpoint. Returns a session id plus a Bearer token used on all subsequent &#x60;/v2/_*&#x60; calls (and as a STOMP CONNECT header for WebSocket). When multi-player isolation is enabled on the server, each session gets its own game engine. 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param sessionRequest  (optional)
     * @return ApiResponse<SessionEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createSessionV2WithHttpInfo(xRequestId: kotlin.String?, sessionRequest: SessionRequest?) : ApiResponse<SessionEnvelope?> {
        val localVariableConfig = createSessionV2RequestConfig(xRequestId = xRequestId, sessionRequest = sessionRequest)

        return request<SessionRequest, SessionEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createSessionV2
     *
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param sessionRequest  (optional)
     * @return RequestConfig
     */
    fun createSessionV2RequestConfig(xRequestId: kotlin.String?, sessionRequest: SessionRequest?) : RequestConfig<SessionRequest> {
        val localVariableBody = sessionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/session",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Explicit logout — drop session, pack prefs, and live engine.
     * Requires a valid Bearer token. Clears session identity, session-scoped pack overrides, and the live game engine. Clients should discard the token afterward. 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return DeleteSessionV2200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteSessionV2(xRequestId: kotlin.String? = null) : DeleteSessionV2200Response {
        val localVarResponse = deleteSessionV2WithHttpInfo(xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DeleteSessionV2200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Explicit logout — drop session, pack prefs, and live engine.
     * Requires a valid Bearer token. Clears session identity, session-scoped pack overrides, and the live game engine. Clients should discard the token afterward. 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<DeleteSessionV2200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteSessionV2WithHttpInfo(xRequestId: kotlin.String?) : ApiResponse<DeleteSessionV2200Response?> {
        val localVariableConfig = deleteSessionV2RequestConfig(xRequestId = xRequestId)

        return request<Unit, DeleteSessionV2200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteSessionV2
     *
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun deleteSessionV2RequestConfig(xRequestId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v2/session",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Disable a content pack; returns the updated catalog.
     * 
     * @param id 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return CatalogEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun disablePackV2(id: kotlin.String, xRequestId: kotlin.String? = null) : CatalogEnvelope {
        val localVarResponse = disablePackV2WithHttpInfo(id = id, xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CatalogEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Disable a content pack; returns the updated catalog.
     * 
     * @param id 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<CatalogEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun disablePackV2WithHttpInfo(id: kotlin.String, xRequestId: kotlin.String?) : ApiResponse<CatalogEnvelope?> {
        val localVariableConfig = disablePackV2RequestConfig(id = id, xRequestId = xRequestId)

        return request<Unit, CatalogEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation disablePackV2
     *
     * @param id 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun disablePackV2RequestConfig(id: kotlin.String, xRequestId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/catalog/packs/{id}/disable".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Enable a content pack; returns the updated catalog.
     * 
     * @param id 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return CatalogEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun enablePackV2(id: kotlin.String, xRequestId: kotlin.String? = null) : CatalogEnvelope {
        val localVarResponse = enablePackV2WithHttpInfo(id = id, xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CatalogEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Enable a content pack; returns the updated catalog.
     * 
     * @param id 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<CatalogEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun enablePackV2WithHttpInfo(id: kotlin.String, xRequestId: kotlin.String?) : ApiResponse<CatalogEnvelope?> {
        val localVariableConfig = enablePackV2RequestConfig(id = id, xRequestId = xRequestId)

        return request<Unit, CatalogEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation enablePackV2
     *
     * @param id 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun enablePackV2RequestConfig(id: kotlin.String, xRequestId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/catalog/packs/{id}/enable".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Installed content packs and registered plugins (mod browser).
     * 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return CatalogEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getCatalogV2(xRequestId: kotlin.String? = null) : CatalogEnvelope {
        val localVarResponse = getCatalogV2WithHttpInfo(xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CatalogEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Installed content packs and registered plugins (mod browser).
     * 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<CatalogEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getCatalogV2WithHttpInfo(xRequestId: kotlin.String?) : ApiResponse<CatalogEnvelope?> {
        val localVariableConfig = getCatalogV2RequestConfig(xRequestId = xRequestId)

        return request<Unit, CatalogEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getCatalogV2
     *
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun getCatalogV2RequestConfig(xRequestId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/catalog",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Health envelope (lean public; detail with ops token).
     * Versioned envelope. Unauthenticated callers get &#x60;status&#x60;, &#x60;uptimeSeconds&#x60;, and &#x60;detail: false&#x60;. With &#x60;X-Metrics-Token&#x60; or &#x60;X-Admin-Token&#x60;, includes sessions, engines, dependencies, memory, and &#x60;detail: true&#x60;. Excluded from JWT enforcement. 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param xMetricsToken Metrics scrape token (&#x60;game.metrics.scrape-token&#x60;). Alternative to &#x60;Authorization: Bearer &lt;token&gt;&#x60;. Unlocks readiness/v2 health detail fields.  (optional)
     * @param xAdminToken Ops shared secret (&#x60;game.admin.token&#x60;). During rotation, &#x60;game.admin.token.previous&#x60; is also accepted. Required for admin routes and (in prod) catalog pack upload; unlocks health recon detail.  (optional)
     * @return HealthEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getHealthV2(xRequestId: kotlin.String? = null, xMetricsToken: kotlin.String? = null, xAdminToken: kotlin.String? = null) : HealthEnvelope {
        val localVarResponse = getHealthV2WithHttpInfo(xRequestId = xRequestId, xMetricsToken = xMetricsToken, xAdminToken = xAdminToken)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HealthEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Health envelope (lean public; detail with ops token).
     * Versioned envelope. Unauthenticated callers get &#x60;status&#x60;, &#x60;uptimeSeconds&#x60;, and &#x60;detail: false&#x60;. With &#x60;X-Metrics-Token&#x60; or &#x60;X-Admin-Token&#x60;, includes sessions, engines, dependencies, memory, and &#x60;detail: true&#x60;. Excluded from JWT enforcement. 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param xMetricsToken Metrics scrape token (&#x60;game.metrics.scrape-token&#x60;). Alternative to &#x60;Authorization: Bearer &lt;token&gt;&#x60;. Unlocks readiness/v2 health detail fields.  (optional)
     * @param xAdminToken Ops shared secret (&#x60;game.admin.token&#x60;). During rotation, &#x60;game.admin.token.previous&#x60; is also accepted. Required for admin routes and (in prod) catalog pack upload; unlocks health recon detail.  (optional)
     * @return ApiResponse<HealthEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getHealthV2WithHttpInfo(xRequestId: kotlin.String?, xMetricsToken: kotlin.String?, xAdminToken: kotlin.String?) : ApiResponse<HealthEnvelope?> {
        val localVariableConfig = getHealthV2RequestConfig(xRequestId = xRequestId, xMetricsToken = xMetricsToken, xAdminToken = xAdminToken)

        return request<Unit, HealthEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getHealthV2
     *
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param xMetricsToken Metrics scrape token (&#x60;game.metrics.scrape-token&#x60;). Alternative to &#x60;Authorization: Bearer &lt;token&gt;&#x60;. Unlocks readiness/v2 health detail fields.  (optional)
     * @param xAdminToken Ops shared secret (&#x60;game.admin.token&#x60;). During rotation, &#x60;game.admin.token.previous&#x60; is also accepted. Required for admin routes and (in prod) catalog pack upload; unlocks health recon detail.  (optional)
     * @return RequestConfig
     */
    fun getHealthV2RequestConfig(xRequestId: kotlin.String?, xMetricsToken: kotlin.String?, xAdminToken: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        xMetricsToken?.apply { localVariableHeaders["X-Metrics-Token"] = this.toString() }
        xAdminToken?.apply { localVariableHeaders["X-Admin-Token"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/health",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Poll async marketplace install progress.
     * Jobs are bound to the session that started them (&#x60;POST …/install?async&#x3D;true&#x60;). Other sessions receive **403**. Legacy rows with no owner remain open. 
     * @param jobId 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return MarketplaceInstallJobEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getMarketplaceInstallJobV2(jobId: kotlin.String, xRequestId: kotlin.String? = null) : MarketplaceInstallJobEnvelope {
        val localVarResponse = getMarketplaceInstallJobV2WithHttpInfo(jobId = jobId, xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MarketplaceInstallJobEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Poll async marketplace install progress.
     * Jobs are bound to the session that started them (&#x60;POST …/install?async&#x3D;true&#x60;). Other sessions receive **403**. Legacy rows with no owner remain open. 
     * @param jobId 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<MarketplaceInstallJobEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getMarketplaceInstallJobV2WithHttpInfo(jobId: kotlin.String, xRequestId: kotlin.String?) : ApiResponse<MarketplaceInstallJobEnvelope?> {
        val localVariableConfig = getMarketplaceInstallJobV2RequestConfig(jobId = jobId, xRequestId = xRequestId)

        return request<Unit, MarketplaceInstallJobEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getMarketplaceInstallJobV2
     *
     * @param jobId 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun getMarketplaceInstallJobV2RequestConfig(jobId: kotlin.String, xRequestId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/marketplace/jobs/{jobId}".replace("{"+"jobId"+"}", encodeURIComponent(jobId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Marketplace pack detail.
     * 
     * @param id 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return MarketplacePackEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getMarketplacePackV2(id: kotlin.String, xRequestId: kotlin.String? = null) : MarketplacePackEnvelope {
        val localVarResponse = getMarketplacePackV2WithHttpInfo(id = id, xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MarketplacePackEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Marketplace pack detail.
     * 
     * @param id 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<MarketplacePackEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getMarketplacePackV2WithHttpInfo(id: kotlin.String, xRequestId: kotlin.String?) : ApiResponse<MarketplacePackEnvelope?> {
        val localVariableConfig = getMarketplacePackV2RequestConfig(id = id, xRequestId = xRequestId)

        return request<Unit, MarketplacePackEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getMarketplacePackV2
     *
     * @param id 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun getMarketplacePackV2RequestConfig(id: kotlin.String, xRequestId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/marketplace/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Echo the authenticated session (no token reflected).
     * 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return SessionEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getSessionMeV2(xRequestId: kotlin.String? = null) : SessionEnvelope {
        val localVarResponse = getSessionMeV2WithHttpInfo(xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SessionEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Echo the authenticated session (no token reflected).
     * 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<SessionEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getSessionMeV2WithHttpInfo(xRequestId: kotlin.String?) : ApiResponse<SessionEnvelope?> {
        val localVariableConfig = getSessionMeV2RequestConfig(xRequestId = xRequestId)

        return request<Unit, SessionEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getSessionMeV2
     *
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun getSessionMeV2RequestConfig(xRequestId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/session/me",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Current game status as a typed envelope.
     * 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return GameStatusEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getStatusV2(xRequestId: kotlin.String? = null) : GameStatusEnvelope {
        val localVarResponse = getStatusV2WithHttpInfo(xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GameStatusEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Current game status as a typed envelope.
     * 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<GameStatusEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getStatusV2WithHttpInfo(xRequestId: kotlin.String?) : ApiResponse<GameStatusEnvelope?> {
        val localVariableConfig = getStatusV2RequestConfig(xRequestId = xRequestId)

        return request<Unit, GameStatusEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getStatusV2
     *
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun getStatusV2RequestConfig(xRequestId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/status",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Install a marketplace pack into the live catalog.
     * Sync by default. Pass &#x60;async&#x3D;true&#x60; for background download with progress (&#x60;GET /v2/marketplace/jobs/{jobId}&#x60;). Async jobs bind to the caller session for poll/cancel ACL. 
     * @param id 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param async When true, returns 202 + job id for progress polling. (optional, default to false)
     * @return MarketplaceInstallEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun installMarketplacePackV2(id: kotlin.String, xRequestId: kotlin.String? = null, async: kotlin.Boolean? = false) : MarketplaceInstallEnvelope {
        val localVarResponse = installMarketplacePackV2WithHttpInfo(id = id, xRequestId = xRequestId, async = async)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MarketplaceInstallEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Install a marketplace pack into the live catalog.
     * Sync by default. Pass &#x60;async&#x3D;true&#x60; for background download with progress (&#x60;GET /v2/marketplace/jobs/{jobId}&#x60;). Async jobs bind to the caller session for poll/cancel ACL. 
     * @param id 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param async When true, returns 202 + job id for progress polling. (optional, default to false)
     * @return ApiResponse<MarketplaceInstallEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun installMarketplacePackV2WithHttpInfo(id: kotlin.String, xRequestId: kotlin.String?, async: kotlin.Boolean?) : ApiResponse<MarketplaceInstallEnvelope?> {
        val localVariableConfig = installMarketplacePackV2RequestConfig(id = id, xRequestId = xRequestId, async = async)

        return request<Unit, MarketplaceInstallEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation installMarketplacePackV2
     *
     * @param id 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param async When true, returns 202 + job id for progress polling. (optional, default to false)
     * @return RequestConfig
     */
    fun installMarketplacePackV2RequestConfig(id: kotlin.String, xRequestId: kotlin.String?, async: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (async != null) {
                    put("async", listOf(async.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/marketplace/{id}/install".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * List the caller&#39;s owned products.
     * 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return EntitlementEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listEntitlementsV2(xRequestId: kotlin.String? = null) : EntitlementEnvelope {
        val localVarResponse = listEntitlementsV2WithHttpInfo(xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as EntitlementEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * List the caller&#39;s owned products.
     * 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<EntitlementEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listEntitlementsV2WithHttpInfo(xRequestId: kotlin.String?) : ApiResponse<EntitlementEnvelope?> {
        val localVariableConfig = listEntitlementsV2RequestConfig(xRequestId = xRequestId)

        return request<Unit, EntitlementEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listEntitlementsV2
     *
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun listEntitlementsV2RequestConfig(xRequestId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/entitlements",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * List local marketplace content packs.
     * Discovers local packs under &#x60;game.content.packs.dir&#x60; plus optional remote index (&#x60;game.marketplace.remote-url&#x60;) with install/enabled status from the live catalog. 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param q Filter by id, name, or description (optional)
     * @return MarketplaceEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listMarketplaceV2(xRequestId: kotlin.String? = null, q: kotlin.String? = null) : MarketplaceEnvelope {
        val localVarResponse = listMarketplaceV2WithHttpInfo(xRequestId = xRequestId, q = q)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MarketplaceEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * List local marketplace content packs.
     * Discovers local packs under &#x60;game.content.packs.dir&#x60; plus optional remote index (&#x60;game.marketplace.remote-url&#x60;) with install/enabled status from the live catalog. 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param q Filter by id, name, or description (optional)
     * @return ApiResponse<MarketplaceEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listMarketplaceV2WithHttpInfo(xRequestId: kotlin.String?, q: kotlin.String?) : ApiResponse<MarketplaceEnvelope?> {
        val localVariableConfig = listMarketplaceV2RequestConfig(xRequestId = xRequestId, q = q)

        return request<Unit, MarketplaceEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listMarketplaceV2
     *
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param q Filter by id, name, or description (optional)
     * @return RequestConfig
     */
    fun listMarketplaceV2RequestConfig(xRequestId: kotlin.String?, q: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (q != null) {
                    put("q", listOf(q.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/marketplace",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * List registered storefronts and live/sandbox mode.
     * 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listStorefrontsV2() : Unit {
        val localVarResponse = listStorefrontsV2WithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * List registered storefronts and live/sandbox mode.
     * 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun listStorefrontsV2WithHttpInfo() : ApiResponse<Unit?> {
        val localVariableConfig = listStorefrontsV2RequestConfig()

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listStorefrontsV2
     *
     * @return RequestConfig
     */
    fun listStorefrontsV2RequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v2/entitlements/storefronts",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Restore the caller&#39;s game engine from its save file.
     * 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return GameStatusEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun loadGameV2(xRequestId: kotlin.String? = null) : GameStatusEnvelope {
        val localVarResponse = loadGameV2WithHttpInfo(xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GameStatusEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Restore the caller&#39;s game engine from its save file.
     * 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<GameStatusEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun loadGameV2WithHttpInfo(xRequestId: kotlin.String?) : ApiResponse<GameStatusEnvelope?> {
        val localVariableConfig = loadGameV2RequestConfig(xRequestId = xRequestId)

        return request<Unit, GameStatusEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation loadGameV2
     *
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun loadGameV2RequestConfig(xRequestId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/load",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Generate a dungeon-master narration via the active LLM provider.
     * 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param narrateRequest  (optional)
     * @return NarrativeEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun narrateV2(xRequestId: kotlin.String? = null, narrateRequest: NarrateRequest? = null) : NarrativeEnvelope {
        val localVarResponse = narrateV2WithHttpInfo(xRequestId = xRequestId, narrateRequest = narrateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NarrativeEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Generate a dungeon-master narration via the active LLM provider.
     * 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param narrateRequest  (optional)
     * @return ApiResponse<NarrativeEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun narrateV2WithHttpInfo(xRequestId: kotlin.String?, narrateRequest: NarrateRequest?) : ApiResponse<NarrativeEnvelope?> {
        val localVariableConfig = narrateV2RequestConfig(xRequestId = xRequestId, narrateRequest = narrateRequest)

        return request<NarrateRequest, NarrativeEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation narrateV2
     *
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param narrateRequest  (optional)
     * @return RequestConfig
     */
    fun narrateV2RequestConfig(xRequestId: kotlin.String?, narrateRequest: NarrateRequest?) : RequestConfig<NarrateRequest> {
        val localVariableBody = narrateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/narrate",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Start a fresh engine for the caller (new party/quest).
     * 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return GameStatusEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun resetGameV2(xRequestId: kotlin.String? = null) : GameStatusEnvelope {
        val localVarResponse = resetGameV2WithHttpInfo(xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GameStatusEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Start a fresh engine for the caller (new party/quest).
     * 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<GameStatusEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun resetGameV2WithHttpInfo(xRequestId: kotlin.String?) : ApiResponse<GameStatusEnvelope?> {
        val localVariableConfig = resetGameV2RequestConfig(xRequestId = xRequestId)

        return request<Unit, GameStatusEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation resetGameV2
     *
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun resetGameV2RequestConfig(xRequestId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/reset",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Persist the caller&#39;s game engine to a session-scoped save file.
     * Authenticated callers save under &#x60;game.saves.dir/{sessionId}.json&#x60;. Unauthenticated callers share the process-default engine and save as &#x60;default.json&#x60;. Each authenticated session has its own engine instance. 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return GameSaveEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun saveGameV2(xRequestId: kotlin.String? = null) : GameSaveEnvelope {
        val localVarResponse = saveGameV2WithHttpInfo(xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GameSaveEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Persist the caller&#39;s game engine to a session-scoped save file.
     * Authenticated callers save under &#x60;game.saves.dir/{sessionId}.json&#x60;. Unauthenticated callers share the process-default engine and save as &#x60;default.json&#x60;. Each authenticated session has its own engine instance. 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<GameSaveEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun saveGameV2WithHttpInfo(xRequestId: kotlin.String?) : ApiResponse<GameSaveEnvelope?> {
        val localVariableConfig = saveGameV2RequestConfig(xRequestId = xRequestId)

        return request<Unit, GameSaveEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation saveGameV2
     *
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun saveGameV2RequestConfig(xRequestId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/save",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Apply a choice; returns the updated game status envelope.
     * 
     * @param actionRequest 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return GameStatusEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun submitActionV2(actionRequest: ActionRequest, xRequestId: kotlin.String? = null) : GameStatusEnvelope {
        val localVarResponse = submitActionV2WithHttpInfo(actionRequest = actionRequest, xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GameStatusEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Apply a choice; returns the updated game status envelope.
     * 
     * @param actionRequest 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<GameStatusEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun submitActionV2WithHttpInfo(actionRequest: ActionRequest, xRequestId: kotlin.String?) : ApiResponse<GameStatusEnvelope?> {
        val localVariableConfig = submitActionV2RequestConfig(actionRequest = actionRequest, xRequestId = xRequestId)

        return request<ActionRequest, GameStatusEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation submitActionV2
     *
     * @param actionRequest 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun submitActionV2RequestConfig(actionRequest: ActionRequest, xRequestId: kotlin.String?) : RequestConfig<ActionRequest> {
        val localVariableBody = actionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/action",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Upload and install a content-pack zip at runtime; returns the updated catalog.
     * Multipart zip install. In production, &#x60;game.catalog.upload.require-admin&#x3D;true&#x60; so callers must send &#x60;X-Admin-Token&#x60; (current or previous during rotation). When &#x60;game.catalog.upload.enabled&#x3D;false&#x60;, always **403**. 
     * @param file Pack zip — pack.yaml plus optional items/, monsters/, strings/, quests/, campaigns/, npcs/, factions/. Pure data; code-bearing mods use the plugin loader instead.
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param xAdminToken Ops shared secret (&#x60;game.admin.token&#x60;). During rotation, &#x60;game.admin.token.previous&#x60; is also accepted. Required for admin routes and (in prod) catalog pack upload; unlocks health recon detail.  (optional)
     * @param replace Overwrite an already-installed pack with the same id. (optional, default to false)
     * @return CatalogEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun uploadPackV2(file: java.io.File, xRequestId: kotlin.String? = null, xAdminToken: kotlin.String? = null, replace: kotlin.Boolean? = false) : CatalogEnvelope {
        val localVarResponse = uploadPackV2WithHttpInfo(file = file, xRequestId = xRequestId, xAdminToken = xAdminToken, replace = replace)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CatalogEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Upload and install a content-pack zip at runtime; returns the updated catalog.
     * Multipart zip install. In production, &#x60;game.catalog.upload.require-admin&#x3D;true&#x60; so callers must send &#x60;X-Admin-Token&#x60; (current or previous during rotation). When &#x60;game.catalog.upload.enabled&#x3D;false&#x60;, always **403**. 
     * @param file Pack zip — pack.yaml plus optional items/, monsters/, strings/, quests/, campaigns/, npcs/, factions/. Pure data; code-bearing mods use the plugin loader instead.
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param xAdminToken Ops shared secret (&#x60;game.admin.token&#x60;). During rotation, &#x60;game.admin.token.previous&#x60; is also accepted. Required for admin routes and (in prod) catalog pack upload; unlocks health recon detail.  (optional)
     * @param replace Overwrite an already-installed pack with the same id. (optional, default to false)
     * @return ApiResponse<CatalogEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun uploadPackV2WithHttpInfo(file: java.io.File, xRequestId: kotlin.String?, xAdminToken: kotlin.String?, replace: kotlin.Boolean?) : ApiResponse<CatalogEnvelope?> {
        val localVariableConfig = uploadPackV2RequestConfig(file = file, xRequestId = xRequestId, xAdminToken = xAdminToken, replace = replace)

        return request<Map<String, PartConfig<*>>, CatalogEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation uploadPackV2
     *
     * @param file Pack zip — pack.yaml plus optional items/, monsters/, strings/, quests/, campaigns/, npcs/, factions/. Pure data; code-bearing mods use the plugin loader instead.
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @param xAdminToken Ops shared secret (&#x60;game.admin.token&#x60;). During rotation, &#x60;game.admin.token.previous&#x60; is also accepted. Required for admin routes and (in prod) catalog pack upload; unlocks health recon detail.  (optional)
     * @param replace Overwrite an already-installed pack with the same id. (optional, default to false)
     * @return RequestConfig
     */
    fun uploadPackV2RequestConfig(file: java.io.File, xRequestId: kotlin.String?, xAdminToken: kotlin.String?, replace: kotlin.Boolean?) : RequestConfig<Map<String, PartConfig<*>>> {
        val localVariableBody = mapOf(
            "file" to PartConfig(body = file, headers = mutableMapOf()),)
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (replace != null) {
                    put("replace", listOf(replace.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "multipart/form-data")
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        xAdminToken?.apply { localVariableHeaders["X-Admin-Token"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/catalog/packs",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Validate a purchase receipt via its storefront and grant the entitlement.
     * 
     * @param verifyReceiptRequest 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return EntitlementEnvelope
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun verifyReceiptV2(verifyReceiptRequest: VerifyReceiptRequest, xRequestId: kotlin.String? = null) : EntitlementEnvelope {
        val localVarResponse = verifyReceiptV2WithHttpInfo(verifyReceiptRequest = verifyReceiptRequest, xRequestId = xRequestId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as EntitlementEnvelope
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Validate a purchase receipt via its storefront and grant the entitlement.
     * 
     * @param verifyReceiptRequest 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return ApiResponse<EntitlementEnvelope?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun verifyReceiptV2WithHttpInfo(verifyReceiptRequest: VerifyReceiptRequest, xRequestId: kotlin.String?) : ApiResponse<EntitlementEnvelope?> {
        val localVariableConfig = verifyReceiptV2RequestConfig(verifyReceiptRequest = verifyReceiptRequest, xRequestId = xRequestId)

        return request<VerifyReceiptRequest, EntitlementEnvelope>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation verifyReceiptV2
     *
     * @param verifyReceiptRequest 
     * @param xRequestId Optional correlation id echoed back in the response envelope&#39;s requestId. A server-generated UUID is used when omitted.  (optional)
     * @return RequestConfig
     */
    fun verifyReceiptV2RequestConfig(verifyReceiptRequest: VerifyReceiptRequest, xRequestId: kotlin.String?) : RequestConfig<VerifyReceiptRequest> {
        val localVariableBody = verifyReceiptRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xRequestId?.apply { localVariableHeaders["X-Request-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v2/entitlements/verify",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
