/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sessionId 
 * @param enabledPackIds 
 * @param overrides 
 * @param sessionScoped 
 */


data class AdminSessionPacksPayload (

    @Json(name = "sessionId")
    val sessionId: kotlin.String? = null,

    @Json(name = "enabledPackIds")
    val enabledPackIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "overrides")
    val overrides: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "sessionScoped")
    val sessionScoped: kotlin.Boolean? = null

) {


}

