/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sessionId 
 * @param displayName 
 * @param createdAtEpochSeconds 
 * @param lastSeenEpochSeconds 
 * @param hasEngine 
 */


data class AdminSessionRow (

    @Json(name = "sessionId")
    val sessionId: kotlin.String? = null,

    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    @Json(name = "createdAtEpochSeconds")
    val createdAtEpochSeconds: kotlin.Long? = null,

    @Json(name = "lastSeenEpochSeconds")
    val lastSeenEpochSeconds: kotlin.Long? = null,

    @Json(name = "hasEngine")
    val hasEngine: kotlin.Boolean? = null

) {


}

