/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import com.xai.dungeonmaster.client.models.AdminSessionRow

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param count 
 * @param total 
 * @param limit 
 * @param sessions 
 */


data class AdminSessionsPayload (

    @Json(name = "count")
    val count: kotlin.Int? = null,

    @Json(name = "total")
    val total: kotlin.Int? = null,

    @Json(name = "limit")
    val limit: kotlin.Int? = null,

    @Json(name = "sessions")
    val sessions: kotlin.collections.List<AdminSessionRow>? = null

) {


}

