/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param idleTtlSeconds 
 * @param removedSessions 
 * @param removedEngines 
 * @param activeSessions 
 * @param activeEngines 
 */


data class AdminSessionsPurgedPayload (

    @Json(name = "idleTtlSeconds")
    val idleTtlSeconds: kotlin.Long? = null,

    @Json(name = "removedSessions")
    val removedSessions: kotlin.Int? = null,

    @Json(name = "removedEngines")
    val removedEngines: kotlin.Int? = null,

    @Json(name = "activeSessions")
    val activeSessions: kotlin.Int? = null,

    @Json(name = "activeEngines")
    val activeEngines: kotlin.Int? = null

) {


}

