/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import com.xai.dungeonmaster.client.models.NarrationInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param version 
 * @param payload 
 * @param requestId 
 */


data class AdminNarrationEnvelope (

    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "version")
    val version: kotlin.Int,

    @Json(name = "payload")
    val payload: NarrationInfo,

    @Json(name = "requestId")
    val requestId: kotlin.String

) {


}

