/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import com.xai.dungeonmaster.client.models.CatalogPayload

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param version Schema version of the payload contract.
 * @param payload 
 * @param requestId Correlation id (echoed from X-Request-Id or generated).
 */


data class CatalogEnvelope (

    @Json(name = "type")
    val type: kotlin.String,

    /* Schema version of the payload contract. */
    @Json(name = "version")
    val version: kotlin.Int,

    @Json(name = "payload")
    val payload: CatalogPayload,

    /* Correlation id (echoed from X-Request-Id or generated). */
    @Json(name = "requestId")
    val requestId: kotlin.String

) {


}

