/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Goal G3 cinematic check (stakes → roll → result).
 *
 * @param kind 
 * @param actor 
 * @param target 
 * @param stakes 
 * @param roll 
 * @param modifier 
 * @param total 
 * @param difficulty 
 * @param success 
 * @param critical 
 * @param fumble 
 * @param effect 
 * @param narration 
 * @param atEpochMs 
 * @param pushedLuck 
 */


data class CheckResultDto (

    @Json(name = "kind")
    val kind: kotlin.String? = null,

    @Json(name = "actor")
    val actor: kotlin.String? = null,

    @Json(name = "target")
    val target: kotlin.String? = null,

    @Json(name = "stakes")
    val stakes: kotlin.String? = null,

    @Json(name = "roll")
    val roll: kotlin.Int? = null,

    @Json(name = "modifier")
    val modifier: kotlin.Int? = null,

    @Json(name = "total")
    val total: kotlin.Int? = null,

    @Json(name = "difficulty")
    val difficulty: kotlin.Int? = null,

    @Json(name = "success")
    val success: kotlin.Boolean? = null,

    @Json(name = "critical")
    val critical: kotlin.Boolean? = null,

    @Json(name = "fumble")
    val fumble: kotlin.Boolean? = null,

    @Json(name = "effect")
    val effect: kotlin.String? = null,

    @Json(name = "narration")
    val narration: kotlin.String? = null,

    @Json(name = "atEpochMs")
    val atEpochMs: kotlin.Long? = null,

    @Json(name = "pushedLuck")
    val pushedLuck: kotlin.Boolean? = null

) {


}

