/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param label 
 * @param stakes Player-facing stakes (not the spoiler result text).
 * @param irreversible UI hint when the choice sets story flags.
 */


data class ChoiceDetail (

    @Json(name = "label")
    val label: kotlin.String? = null,

    /* Player-facing stakes (not the spoiler result text). */
    @Json(name = "stakes")
    val stakes: kotlin.String? = null,

    /* UI hint when the choice sets story flags. */
    @Json(name = "irreversible")
    val irreversible: kotlin.Boolean? = null

) {


}

