/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param loggedOut 
 * @param sessionId 
 */


data class DeleteSessionV2200ResponsePayload (

    @Json(name = "loggedOut")
    val loggedOut: kotlin.Boolean? = null,

    @Json(name = "sessionId")
    val sessionId: kotlin.String? = null

) {


}

