/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status 
 * @param detail 
 */


data class DependencyCheck (

    @Json(name = "status")
    val status: DependencyCheck.Status,

    @Json(name = "detail")
    val detail: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: UP,DOWN,NOT_CONFIGURED
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "UP") UP("UP"),
        @Json(name = "DOWN") DOWN("DOWN"),
        @Json(name = "NOT_CONFIGURED") NOT_CONFIGURED("NOT_CONFIGURED");
    }

}

