/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Base transport envelope. Concrete responses specialize `payload`.
 *
 * @param type Payload discriminator (game_status, narrative_update, error).
 * @param version Schema version of the payload contract.
 * @param payload Typed body; shape depends on `type`.
 * @param requestId Correlation id (echoed from X-Request-Id or generated).
 */


data class Envelope (

    /* Payload discriminator (game_status, narrative_update, error). */
    @Json(name = "type")
    val type: kotlin.String,

    /* Schema version of the payload contract. */
    @Json(name = "version")
    val version: kotlin.Int,

    /* Typed body; shape depends on `type`. */
    @Json(name = "payload")
    val payload: kotlin.Any,

    /* Correlation id (echoed from X-Request-Id or generated). */
    @Json(name = "requestId")
    val requestId: kotlin.String

) {


}

