/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param exists 
 * @param path 
 * @param sessionScoped 
 * @param bytes 
 * @param modifiedAtEpochMs 
 */


data class GameSaveMetaEnvelopeAllOfPayload (

    @Json(name = "exists")
    val exists: kotlin.Boolean? = null,

    @Json(name = "path")
    val path: kotlin.String? = null,

    @Json(name = "sessionScoped")
    val sessionScoped: kotlin.Boolean? = null,

    @Json(name = "bytes")
    val bytes: kotlin.Long? = null,

    @Json(name = "modifiedAtEpochMs")
    val modifiedAtEpochMs: kotlin.Long? = null

) {


}

