/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param deleted 
 * @param exists 
 * @param path 
 * @param sessionScoped 
 * @param error 
 */


data class GameSaveDeleteEnvelopeAllOfPayload (

    @Json(name = "deleted")
    val deleted: kotlin.Boolean? = null,

    @Json(name = "exists")
    val exists: kotlin.Boolean? = null,

    @Json(name = "path")
    val path: kotlin.String? = null,

    @Json(name = "sessionScoped")
    val sessionScoped: kotlin.Boolean? = null,

    @Json(name = "error")
    val error: kotlin.String? = null

) {


}

