/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import com.xai.dungeonmaster.client.models.MemberState

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param party 
 * @param chaosLevel 
 * @param combatActive 
 * @param availableChoices 
 * @param recentHistory 
 */


data class GameStatusV2 (

    @Json(name = "party")
    val party: kotlin.collections.List<MemberState>? = null,

    @Json(name = "chaosLevel")
    val chaosLevel: kotlin.Int? = null,

    @Json(name = "combatActive")
    val combatActive: kotlin.Boolean? = null,

    @Json(name = "availableChoices")
    val availableChoices: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "recentHistory")
    val recentHistory: kotlin.collections.List<kotlin.String>? = null

) {


}

