/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param saved 
 * @param path 
 * @param sessionScoped 
 */


data class GameSaveEnvelopeAllOfPayload (

    @Json(name = "saved")
    val saved: kotlin.Boolean? = null,

    @Json(name = "path")
    val path: kotlin.String? = null,

    @Json(name = "sessionScoped")
    val sessionScoped: kotlin.Boolean? = null

) {


}

