/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Legacy flat status; `partySummary` is a pipe-delimited string.
 *
 * @param partySummary 
 * @param chaosLevel 
 * @param combatActive 
 * @param availableChoices 
 * @param recentHistory 
 */


data class GameStatusResponse (

    @Json(name = "partySummary")
    val partySummary: kotlin.String? = null,

    @Json(name = "chaosLevel")
    val chaosLevel: kotlin.Int? = null,

    @Json(name = "combatActive")
    val combatActive: kotlin.Boolean? = null,

    @Json(name = "availableChoices")
    val availableChoices: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "recentHistory")
    val recentHistory: kotlin.collections.List<kotlin.String>? = null

) {


}

