/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status 
 * @param probe 
 */


data class LivenessResponse (

    @Json(name = "status")
    val status: LivenessResponse.Status,

    @Json(name = "probe")
    val probe: LivenessResponse.Probe

) {

    /**
     * 
     *
     * Values: UP
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "UP") UP("UP");
    }
    /**
     * 
     *
     * Values: liveness
     */
    @JsonClass(generateAdapter = false)
    enum class Probe(val value: kotlin.String) {
        @Json(name = "liveness") liveness("liveness");
    }

}

