/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.xai.dungeonmaster.client.models.MarketplaceInstallJobsPayload
import com.xai.dungeonmaster.client.models.MarketplaceInstallJob

class MarketplaceInstallJobsPayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MarketplaceInstallJobsPayload
        //val modelInstance = MarketplaceInstallJobsPayload()

        // to test the property `count`
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `limit`
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

        // to test the property `jobs`
        should("test jobs") {
            // uncomment below to test the property
            //modelInstance.jobs shouldBe ("TODO")
        }

    }
}
