/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import com.xai.dungeonmaster.client.models.MarketplaceListing

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param root 
 * @param remoteIndexUrl 
 * @param remoteOk 
 * @param remoteError 
 * @param available 
 * @param installed 
 * @param packs 
 */


data class MarketplacePayload (

    @Json(name = "root")
    val root: kotlin.String? = null,

    @Json(name = "remoteIndexUrl")
    val remoteIndexUrl: kotlin.String? = null,

    @Json(name = "remoteOk")
    val remoteOk: kotlin.Boolean? = null,

    @Json(name = "remoteError")
    val remoteError: kotlin.String? = null,

    @Json(name = "available")
    val available: kotlin.Int? = null,

    @Json(name = "installed")
    val installed: kotlin.Int? = null,

    @Json(name = "packs")
    val packs: kotlin.collections.List<MarketplaceListing>? = null

) {


}

