/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models

import com.xai.dungeonmaster.client.models.MarketplacePayload

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param packId 
 * @param alreadyInstalled 
 * @param message 
 * @param marketplace 
 */


data class MarketplaceInstallResult (

    @Json(name = "packId")
    val packId: kotlin.String? = null,

    @Json(name = "alreadyInstalled")
    val alreadyInstalled: kotlin.Boolean? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "marketplace")
    val marketplace: MarketplacePayload? = null

) {


}

