/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param jobId 
 * @param packId 
 * @param phase 
 * @param percent 
 * @param bytesRead 
 * @param bytesTotal 
 * @param message 
 * @param cancelRequested 
 * @param error 
 */


data class MarketplaceInstallJob (

    @Json(name = "jobId")
    val jobId: kotlin.String,

    @Json(name = "packId")
    val packId: kotlin.String,

    @Json(name = "phase")
    val phase: MarketplaceInstallJob.Phase,

    @Json(name = "percent")
    val percent: kotlin.Int,

    @Json(name = "bytesRead")
    val bytesRead: kotlin.Long? = null,

    @Json(name = "bytesTotal")
    val bytesTotal: kotlin.Long? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "cancelRequested")
    val cancelRequested: kotlin.Boolean? = null,

    @Json(name = "error")
    val error: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: QUEUED,DOWNLOADING,VERIFYING,INSTALLING,DONE,FAILED,CANCELLED
     */
    @JsonClass(generateAdapter = false)
    enum class Phase(val value: kotlin.String) {
        @Json(name = "QUEUED") QUEUED("QUEUED"),
        @Json(name = "DOWNLOADING") DOWNLOADING("DOWNLOADING"),
        @Json(name = "VERIFYING") VERIFYING("VERIFYING"),
        @Json(name = "INSTALLING") INSTALLING("INSTALLING"),
        @Json(name = "DONE") DONE("DONE"),
        @Json(name = "FAILED") FAILED("FAILED"),
        @Json(name = "CANCELLED") CANCELLED("CANCELLED");
    }

}

