/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Public snapshot of a single party member.
 *
 * @param name 
 * @param role 
 * @param level 
 * @param hp 
 * @param maxHp 
 * @param mana 
 * @param maxMana 
 * @param armorClass 
 * @param alive 
 * @param ascendant 
 * @param statuses 
 */


data class MemberState (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "role")
    val role: kotlin.String? = null,

    @Json(name = "level")
    val level: kotlin.Int? = null,

    @Json(name = "hp")
    val hp: kotlin.Int? = null,

    @Json(name = "maxHp")
    val maxHp: kotlin.Int? = null,

    @Json(name = "mana")
    val mana: kotlin.Int? = null,

    @Json(name = "maxMana")
    val maxMana: kotlin.Int? = null,

    @Json(name = "armorClass")
    val armorClass: kotlin.Int? = null,

    @Json(name = "alive")
    val alive: kotlin.Boolean? = null,

    @Json(name = "ascendant")
    val ascendant: kotlin.Boolean? = null,

    @Json(name = "statuses")
    val statuses: kotlin.collections.List<kotlin.String>? = null

) {


}

