/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One installed content pack.
 *
 * @param id 
 * @param displayName 
 * @param version 
 * @param monsters 
 * @param items 
 * @param enabled 
 */


data class PackInfo (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    @Json(name = "version")
    val version: kotlin.String? = null,

    @Json(name = "monsters")
    val monsters: kotlin.Int? = null,

    @Json(name = "items")
    val items: kotlin.Int? = null,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null

) {


}

