/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Goal G2 — player-facing identity and session recap.
 *
 * @param partyTitle e.g. \"Ryn the Ash-Handed\"
 * @param epithets 
 * @param scars 
 * @param recap Up to ~3 short sentences for load / chrome.
 */


data class StoryMemoryPayload (

    /* e.g. \"Ryn the Ash-Handed\" */
    @Json(name = "partyTitle")
    val partyTitle: kotlin.String? = null,

    @Json(name = "epithets")
    val epithets: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "scars")
    val scars: kotlin.collections.List<kotlin.String>? = null,

    /* Up to ~3 short sentences for load / chrome. */
    @Json(name = "recap")
    val recap: kotlin.collections.List<kotlin.String>? = null

) {


}

