/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.xai.dungeonmaster.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productId 
 * @param receipt 
 * @param storefront 
 */


data class VerifyReceiptRequest (

    @Json(name = "productId")
    val productId: kotlin.String,

    @Json(name = "receipt")
    val receipt: kotlin.String,

    @Json(name = "storefront")
    val storefront: kotlin.String? = null

) {


}

