//
// AdminReceiptRow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminReceiptRow: Codable, JSONEncodable, Hashable {

    public var fingerprint: String?
    public var sessionId: String?
    public var productId: String?
    public var storefront: String?
    public var redeemedAtEpochMs: Int64?

    public init(fingerprint: String? = nil, sessionId: String? = nil, productId: String? = nil, storefront: String? = nil, redeemedAtEpochMs: Int64? = nil) {
        self.fingerprint = fingerprint
        self.sessionId = sessionId
        self.productId = productId
        self.storefront = storefront
        self.redeemedAtEpochMs = redeemedAtEpochMs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fingerprint
        case sessionId
        case productId
        case storefront
        case redeemedAtEpochMs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fingerprint, forKey: .fingerprint)
        try container.encodeIfPresent(sessionId, forKey: .sessionId)
        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encodeIfPresent(storefront, forKey: .storefront)
        try container.encodeIfPresent(redeemedAtEpochMs, forKey: .redeemedAtEpochMs)
    }
}

