//
// AdminSessionRow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminSessionRow: Codable, JSONEncodable, Hashable {

    public var sessionId: String?
    public var displayName: String?
    public var createdAtEpochSeconds: Int64?
    public var lastSeenEpochSeconds: Int64?
    public var hasEngine: Bool?

    public init(sessionId: String? = nil, displayName: String? = nil, createdAtEpochSeconds: Int64? = nil, lastSeenEpochSeconds: Int64? = nil, hasEngine: Bool? = nil) {
        self.sessionId = sessionId
        self.displayName = displayName
        self.createdAtEpochSeconds = createdAtEpochSeconds
        self.lastSeenEpochSeconds = lastSeenEpochSeconds
        self.hasEngine = hasEngine
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionId
        case displayName
        case createdAtEpochSeconds
        case lastSeenEpochSeconds
        case hasEngine
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sessionId, forKey: .sessionId)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(createdAtEpochSeconds, forKey: .createdAtEpochSeconds)
        try container.encodeIfPresent(lastSeenEpochSeconds, forKey: .lastSeenEpochSeconds)
        try container.encodeIfPresent(hasEngine, forKey: .hasEngine)
    }
}

