//
// AdminSessionPacksPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminSessionPacksPayload: Codable, JSONEncodable, Hashable {

    public var sessionId: String?
    public var enabledPackIds: [String]?
    public var overrides: [String: AnyCodable]?
    public var sessionScoped: Bool?

    public init(sessionId: String? = nil, enabledPackIds: [String]? = nil, overrides: [String: AnyCodable]? = nil, sessionScoped: Bool? = nil) {
        self.sessionId = sessionId
        self.enabledPackIds = enabledPackIds
        self.overrides = overrides
        self.sessionScoped = sessionScoped
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionId
        case enabledPackIds
        case overrides
        case sessionScoped
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sessionId, forKey: .sessionId)
        try container.encodeIfPresent(enabledPackIds, forKey: .enabledPackIds)
        try container.encodeIfPresent(overrides, forKey: .overrides)
        try container.encodeIfPresent(sessionScoped, forKey: .sessionScoped)
    }
}

