//
// AdminSessionsPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminSessionsPayload: Codable, JSONEncodable, Hashable {

    public var count: Int?
    public var total: Int?
    public var limit: Int?
    public var sessions: [AdminSessionRow]?

    public init(count: Int? = nil, total: Int? = nil, limit: Int? = nil, sessions: [AdminSessionRow]? = nil) {
        self.count = count
        self.total = total
        self.limit = limit
        self.sessions = sessions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case total
        case limit
        case sessions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(sessions, forKey: .sessions)
    }
}

