//
// AdminReceiptsPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminReceiptsPayload: Codable, JSONEncodable, Hashable {

    public var count: Int?
    public var limit: Int?
    public var productId: String?
    public var storefront: String?
    public var sessionId: String?
    public var since: Int64?
    public var until: Int64?
    public var receipts: [AdminReceiptRow]?

    public init(count: Int? = nil, limit: Int? = nil, productId: String? = nil, storefront: String? = nil, sessionId: String? = nil, since: Int64? = nil, until: Int64? = nil, receipts: [AdminReceiptRow]? = nil) {
        self.count = count
        self.limit = limit
        self.productId = productId
        self.storefront = storefront
        self.sessionId = sessionId
        self.since = since
        self.until = until
        self.receipts = receipts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case limit
        case productId
        case storefront
        case sessionId
        case since
        case until
        case receipts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encodeIfPresent(storefront, forKey: .storefront)
        try container.encodeIfPresent(sessionId, forKey: .sessionId)
        try container.encodeIfPresent(since, forKey: .since)
        try container.encodeIfPresent(until, forKey: .until)
        try container.encodeIfPresent(receipts, forKey: .receipts)
    }
}

