//
// EntitlementPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EntitlementPayload: Codable, JSONEncodable, Hashable {

    public var granted: Bool?
    public var productId: String?
    public var storefront: String?
    public var reason: String?
    public var owned: [String]?

    public init(granted: Bool? = nil, productId: String? = nil, storefront: String? = nil, reason: String? = nil, owned: [String]? = nil) {
        self.granted = granted
        self.productId = productId
        self.storefront = storefront
        self.reason = reason
        self.owned = owned
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case granted
        case productId
        case storefront
        case reason
        case owned
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(granted, forKey: .granted)
        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encodeIfPresent(storefront, forKey: .storefront)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(owned, forKey: .owned)
    }
}

