//
// Envelope.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Base transport envelope. Concrete responses specialize &#x60;payload&#x60;. */
public struct Envelope: Codable, JSONEncodable, Hashable {

    /** Payload discriminator (game_status, narrative_update, error). */
    public var type: String
    /** Schema version of the payload contract. */
    public var version: Int
    /** Typed body; shape depends on `type`. */
    public var payload: AnyCodable
    /** Correlation id (echoed from X-Request-Id or generated). */
    public var requestId: String

    public init(type: String, version: Int, payload: AnyCodable, requestId: String) {
        self.type = type
        self.version = version
        self.payload = payload
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case version
        case payload
        case requestId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(version, forKey: .version)
        try container.encode(payload, forKey: .payload)
        try container.encode(requestId, forKey: .requestId)
    }
}

