//
// GameStatusV2.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GameStatusV2: Codable, JSONEncodable, Hashable {

    public var party: [MemberState]?
    public var chaosLevel: Int?
    public var combatActive: Bool?
    public var availableChoices: [String]?
    public var recentHistory: [String]?

    public init(party: [MemberState]? = nil, chaosLevel: Int? = nil, combatActive: Bool? = nil, availableChoices: [String]? = nil, recentHistory: [String]? = nil) {
        self.party = party
        self.chaosLevel = chaosLevel
        self.combatActive = combatActive
        self.availableChoices = availableChoices
        self.recentHistory = recentHistory
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case party
        case chaosLevel
        case combatActive
        case availableChoices
        case recentHistory
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(party, forKey: .party)
        try container.encodeIfPresent(chaosLevel, forKey: .chaosLevel)
        try container.encodeIfPresent(combatActive, forKey: .combatActive)
        try container.encodeIfPresent(availableChoices, forKey: .availableChoices)
        try container.encodeIfPresent(recentHistory, forKey: .recentHistory)
    }
}

