//
// GameSaveMetaEnvelopeAllOfPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GameSaveMetaEnvelopeAllOfPayload: Codable, JSONEncodable, Hashable {

    public var exists: Bool?
    public var path: String?
    public var sessionScoped: Bool?
    public var bytes: Int64?
    public var modifiedAtEpochMs: Int64?

    public init(exists: Bool? = nil, path: String? = nil, sessionScoped: Bool? = nil, bytes: Int64? = nil, modifiedAtEpochMs: Int64? = nil) {
        self.exists = exists
        self.path = path
        self.sessionScoped = sessionScoped
        self.bytes = bytes
        self.modifiedAtEpochMs = modifiedAtEpochMs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case exists
        case path
        case sessionScoped
        case bytes
        case modifiedAtEpochMs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(exists, forKey: .exists)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(sessionScoped, forKey: .sessionScoped)
        try container.encodeIfPresent(bytes, forKey: .bytes)
        try container.encodeIfPresent(modifiedAtEpochMs, forKey: .modifiedAtEpochMs)
    }
}

