//
// HealthPayloadMemory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HealthPayloadMemory: Codable, JSONEncodable, Hashable {

    public var maxBytes: Int64?
    public var totalBytes: Int64?
    public var freeBytes: Int64?

    public init(maxBytes: Int64? = nil, totalBytes: Int64? = nil, freeBytes: Int64? = nil) {
        self.maxBytes = maxBytes
        self.totalBytes = totalBytes
        self.freeBytes = freeBytes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maxBytes
        case totalBytes
        case freeBytes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(maxBytes, forKey: .maxBytes)
        try container.encodeIfPresent(totalBytes, forKey: .totalBytes)
        try container.encodeIfPresent(freeBytes, forKey: .freeBytes)
    }
}

