//
// MarketplaceListing.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MarketplaceListing: Codable, JSONEncodable, Hashable {

    public enum Source: String, Codable, CaseIterable {
        case local = "local"
        case remote = "remote"
    }
    public var id: String
    public var displayName: String
    public var version: String
    public var minEngineVersion: String?
    public var description: String?
    public var installed: Bool
    public var enabled: Bool
    public var sourcePath: String?
    public var source: Source
    public var downloadUrl: String?
    public var sha256: String?

    public init(id: String, displayName: String, version: String, minEngineVersion: String? = nil, description: String? = nil, installed: Bool, enabled: Bool, sourcePath: String? = nil, source: Source, downloadUrl: String? = nil, sha256: String? = nil) {
        self.id = id
        self.displayName = displayName
        self.version = version
        self.minEngineVersion = minEngineVersion
        self.description = description
        self.installed = installed
        self.enabled = enabled
        self.sourcePath = sourcePath
        self.source = source
        self.downloadUrl = downloadUrl
        self.sha256 = sha256
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case displayName
        case version
        case minEngineVersion
        case description
        case installed
        case enabled
        case sourcePath
        case source
        case downloadUrl
        case sha256
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(version, forKey: .version)
        try container.encodeIfPresent(minEngineVersion, forKey: .minEngineVersion)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(installed, forKey: .installed)
        try container.encode(enabled, forKey: .enabled)
        try container.encodeIfPresent(sourcePath, forKey: .sourcePath)
        try container.encode(source, forKey: .source)
        try container.encodeIfPresent(downloadUrl, forKey: .downloadUrl)
        try container.encodeIfPresent(sha256, forKey: .sha256)
    }
}

