//
// MarketplaceInstallResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MarketplaceInstallResult: Codable, JSONEncodable, Hashable {

    public var packId: String?
    public var alreadyInstalled: Bool?
    public var message: String?
    public var marketplace: MarketplacePayload?

    public init(packId: String? = nil, alreadyInstalled: Bool? = nil, message: String? = nil, marketplace: MarketplacePayload? = nil) {
        self.packId = packId
        self.alreadyInstalled = alreadyInstalled
        self.message = message
        self.marketplace = marketplace
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case packId
        case alreadyInstalled
        case message
        case marketplace
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(packId, forKey: .packId)
        try container.encodeIfPresent(alreadyInstalled, forKey: .alreadyInstalled)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(marketplace, forKey: .marketplace)
    }
}

