//
// NarrativePayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NarrativePayload: Codable, JSONEncodable, Hashable {

    public var text: String?
    /** Active provider id, e.g. local-stub. */
    public var provider: String?
    public var tokensUsed: Int?
    /** True when a guardrail/fallback response was returned. */
    public var fallback: Bool?

    public init(text: String? = nil, provider: String? = nil, tokensUsed: Int? = nil, fallback: Bool? = nil) {
        self.text = text
        self.provider = provider
        self.tokensUsed = tokensUsed
        self.fallback = fallback
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case text
        case provider
        case tokensUsed
        case fallback
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(tokensUsed, forKey: .tokensUsed)
        try container.encodeIfPresent(fallback, forKey: .fallback)
    }
}

