//
// PackInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One installed content pack. */
public struct PackInfo: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var displayName: String?
    public var version: String?
    public var monsters: Int?
    public var items: Int?

    public init(id: String? = nil, displayName: String? = nil, version: String? = nil, monsters: Int? = nil, items: Int? = nil) {
        self.id = id
        self.displayName = displayName
        self.version = version
        self.monsters = monsters
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case displayName
        case version
        case monsters
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(monsters, forKey: .monsters)
        try container.encodeIfPresent(items, forKey: .items)
    }
}

