//
// SessionPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SessionPayload: Codable, JSONEncodable, Hashable {

    /** Stable player session id (JWT subject). */
    public var sessionId: String
    /** JWT (only set on create; null on /session/me). */
    public var token: String?
    public var displayName: String
    public var expiresAtEpochSeconds: Int64?
    public var createdAtEpochSeconds: Int64?

    public init(sessionId: String, token: String? = nil, displayName: String, expiresAtEpochSeconds: Int64? = nil, createdAtEpochSeconds: Int64? = nil) {
        self.sessionId = sessionId
        self.token = token
        self.displayName = displayName
        self.expiresAtEpochSeconds = expiresAtEpochSeconds
        self.createdAtEpochSeconds = createdAtEpochSeconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionId
        case token
        case displayName
        case expiresAtEpochSeconds
        case createdAtEpochSeconds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sessionId, forKey: .sessionId)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encode(displayName, forKey: .displayName)
        try container.encodeIfPresent(expiresAtEpochSeconds, forKey: .expiresAtEpochSeconds)
        try container.encodeIfPresent(createdAtEpochSeconds, forKey: .createdAtEpochSeconds)
    }
}

